### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by vasisualiy** [GrayHatter/uTox#105]
Why is the versioning changed? What is the reason for it? I think its a some kind of wrong way, to do it, like it firefox do. Great numbers are some kind of tackiness/kitsch imho.

**Comment by cebe** [comment]
its still a 0.x version, where do you see great numbers?

**Comment by vasisualiy** [comment]
There was 0.4.7, then 0.5.0. And the next release must be a 0.6.0, and nothing with 0.5.1. And I already feel the future with a 20.0.0 :D

**Comment by GrayHatter** [comment]
uTox is going to use http://semver.org/ but it's also going to get release names as well.

**Comment by vasisualiy** [comment]
roger it! thx :)
