### ISSUE TITLE
uTox crash on start

### ISSUE THREAD

**Issue by redmanmale** [GrayHatter/uTox#109]
v.640.5.0 crashes on start on Win 8.1 x64.
![crash screen](https://puu.sh/m5JwW/bde20a2ebe.png)

**Comment by GrayHatter** [comment]
@irungentoo 

@redmanmale is this the updater build?

**Comment by GrayHatter** [comment]
does this one crash? https://build.tox.chat/job/uTox_build_windows_x86-64_debug/lastSuccessfulBuild/artifact/utox_windows_x86-64_debug.zip

**Comment by ElLamparto** [comment]
Last Sunday (20/12) I remotely upgraded my friend (Win7, 64bit) and uTox did not start. I could not investigate unfortunately, just reverted to previous version.

**Comment by redmanmale** [comment]
@GrayHatter 
This version doesn't crush, but to start successfully it must be run with administrator rights, it takes a very long time (~3-4 minutes) to start; and it doesn't go online (i.e. in fact it doesn't work at all).

**Comment by redmanmale** [comment]
I was too hasty to say it works. Once it works, once it doesn't.
And all that time from start to show up window it eats 25% CPU.

**Comment by GrayHatter** [comment]
@redmanmale can you find me in #tox-dev on IRC. I'd like to get this fixed

**Comment by GrayHatter** [comment]
should be fixed in df5e744
