### ISSUE TITLE
[Feature request] Font size settings

### ISSUE THREAD

**Issue by redmanmale** [GrayHatter/uTox#114]
It would be very useful to tune up font size of text.
Now it could be done only by using DPI settings and the step is too large to be comfortable.
Or it would be DPI scale from 100% to 150% with 10% step or custom input value (now it combobox with preset values).

**Comment by GrayHatter** [comment]
@redmanmale that's on my radar, unfortunately, it would involve rewriting almost all of µTox. It was never meant to constantly change size, and there's a lot of values that don't respond well to changing from `int` to `float`.

**Comment by GrayHatter** [comment]
this was done in v0.7
