### ISSUE TITLE
Tooltip in system tray is always colon

### ISSUE THREAD

**Issue by redmanmale** [GrayHatter/uTox#115]
Tooltip in system tray is always like that:
![screen](https://puu.sh/m7sR2/4467c8470a.png)

uTox v.0.5.0 (debug version from https://github.com/GrayHatter/uTox/issues/109#issuecomment-166828769), Win 8.1 x64, Win 7 x64.

**Comment by stal888** [comment]
maybe fixed by b815cfd

**Comment by GrayHatter** [comment]
should be fixed ping me if not
