### ISSUE TITLE
Old "Normal" DPI is at 90%

### ISSUE THREAD

**Issue by tsudoko** [GrayHatter/uTox#125]
28fc283
Not sure if it's exactly 90%, but I can't set more accurate values.

**Comment by GrayHatter** [comment]
@tsudoko that's likely to be it. We could change the % numbers to match, but I'm not convinced we should... thoughts?

**Comment by cebe** [comment]
> Not sure if it's exactly 90%, but I can't set more accurate values.

same here. 90% aligns visually with normal text size in other windows. 100% is a bit too big as the default imo.

**Comment by GrayHatter** [comment]
@cebe get some more people to agree with you, I'm on a high dpu screen, and
it looks better this way.

Also maybe someone wants to open an issue for literal custom DPI values?

**Comment by stal888** [comment]
On OS X the current 100% looks more normal than before.

**Comment by GrayHatter** [comment]
same on my surface pro

**Comment by stal888** [comment]
\> he fell for the surface meme

**Comment by cebe** [comment]
I checked the UI in more detail, and imo its only the settings headlines that look unnormal (a bit too big).

**Comment by cebe** [comment]
just noticed its different. on current develop the start DPI is weird, if I change settings everything becomes normal:

starting utox:

![bildschirmfoto von 2016-01-13 13 55 09](https://cloud.githubusercontent.com/assets/189796/12294843/8171c4d6-b9fd-11e5-910d-89214e461ee7.png)

switching to 90% DPI:
![bildschirmfoto von 2016-01-13 13 55 22](https://cloud.githubusercontent.com/assets/189796/12294845/8179b272-b9fd-11e5-92a6-f738a04f6b75.png)

switching "back" to 100% DPI:
![bildschirmfoto von 2016-01-13 13 55 32](https://cloud.githubusercontent.com/assets/189796/12294844/8174db1c-b9fd-11e5-9463-1ddb5b5055b3.png)

100% on start is different from 100% when switched in settings...

**Comment by GrayHatter** [comment]
ew, thanks. I think I know what's wrong...
