### ISSUE TITLE
UI looks bad on some DPI settings

### ISSUE THREAD

**Issue by tsudoko** [GrayHatter/uTox#126]
28fc283
80%
![image](https://cocaine.ninja/files/qwztrg.png)
110%
![image](https://cocaine.ninja/files/agaere.png)

**Comment by GrayHatter** [comment]
I'm going to defer this to the next release.

Best guess is that the inner diameter of the notice circle is an odd number sometimes. So the only way to fix this is likely to be avoiding the use of `SCALE` for this icon/bitmap

**Comment by GrayHatter** [comment]
I've got this "mostly fixed" so I'm going to close it.

It's still not 100% because I don't know how to math this better. see commit d759eeccd997b137bdad53e1395e141f14e85269
