### ISSUE TITLE
uTox password security aspects

### ISSUE THREAD

**Issue by NicoHood** [GrayHatter/uTox#130]
While suing utox for the first time I noticed a few things:
 - [ ] Logging in requires a password. If its correct (without pressing enter), it will open utox. That is dangerous and weird for the user.
 - [ ] utox opens in the settings. There you can change the password without requiering the old password
 - [ ] **You also do not need to retype the password a 2nd time, also dangerous if you accidentally delete a char.**
 - [ ] It leaks the password length
 - [ ] The lock button has nothing to do with the password warning. I expected it has something to do with the red password warning.
 - [ ] The lock button has a mouseover, but it doesnt clearly tell me if its just equal to just closing utox (please anser this question as well please)
 - [ ] I cannot set (or do not know where) the history time. It would be nice to delete if after X hours, days or just destroy it after saving/or if the client is still open after x hours. For secure aware people this is important. I personally do never want to save history, or at least max 1 day.

~~A Wrong password timeout should be applied.~~

Other bugs:
* When pressing (and holding) the language button, it shows a menu above, but i cannot scrol up to the top, its beyond the window limit of the program headline
* Audio/Video Setting: Pressing the phone preview button does nothing. I dont know what it is supposed to do, but it would be nice to check the audio level, like a testring.
* Feature: Mini contact view would be nice,

**Comment by tsudoko** [comment]
Please try to keep different bugs/feature requests in separate issue reports.
> I personally do never want to save history

You can disable logging in the "User Interface" tab.

**Comment by GrayHatter** [comment]
@tsudoko normally you're correct but in this case I asked him to use just one. I've gotta rework the password box, and I don't want to go issue hunting because I'm sure to miss something!

Also, I like the new cat:

**Comment by GrayHatter** [comment]
I just deleted a suggestion, password lockouts are to prevent brute force logins. If you're going to brute force your way in, you'll either just restart the app (super easy, and  I'm not saving lockouts across client restarts), or use a different client.

**Comment by Chryseus** [comment]
I would suggest adding an option to remember your password, it's highly inconvenient having to put it in after every reboot, one might argue it improves security which in many ways is indeed true, but not in all cases, for example my system is encrypted so there is no security risk by remembering a password.

**Comment by GrayHatter** [comment]
Then why add a password to uTox at all?

**Comment by Chryseus** [comment]
For users that don't have disk encryption a password is still important for security, I think the option should be there simply as a user convenience since not everyone using uTox requires such a level of security, even with encryption I may from time to time want to lock my account, for example when sharing the computer with another person.

**Comment by NicoHood** [comment]
Disabling a password should only be possible to enable if autodeletion is enabled (max 7 days).
But I agree on that. I also disabled my password but also the complete history. Since tox uses perfect forward security this requires the attacker to get my private key AND do an ACTIVE mitm attack.
