### ISSUE TITLE
Android issues

### ISSUE THREAD

**Issue by nachfuellbar** [GrayHatter/uTox#131]
Just wanted to give some feedback:

- System language isn't used https://github.com/GrayHatter/uTox/issues/132
- Settings aren't scrollable (needed with huge dpi)
- Copy of tox id doesn't work (after sending Tox ID of my Desktop Client, i can't paste it as well) https://github.com/GrayHatter/uTox/issues/133
- Video input devices aren't detected https://github.com/GrayHatter/uTox/issues/134
- No audio filter available https://github.com/GrayHatter/uTox/issues/135
- Keyboard overlays bottom of utox https://github.com/GrayHatter/uTox/issues/136

If i should separate issues, just say it

**Comment by GrayHatter** [comment]
@nachfuellbar yeah, these should be separated, especially as the settings not being scrollable at high DPI isn't an android issue.

**Comment by nachfuellbar** [comment]
separate issues created
