### ISSUE TITLE
Adding my best friend failed

### ISSUE THREAD

**Issue by subliun** [GrayHatter/uTox#147]
I tried to add my friend, subliun@toxme.io, and uTox complained that the dns lookup failed and spat out some message about being "stuck in the past". idk what that means, but I need to talk to my  Australian pal before he dies of type 2 diacancer and oversnark. 

pls fix

**Comment by cebe** [comment]
Seems urgent enough for you to send a PR. Contributions welcome ;)

**Comment by cebe** [comment]
duplicete of #145 btw

**Comment by GrayHatter** [comment]
closed as known troll account

**Comment by stal888** [comment]
memes
