### ISSUE TITLE
UTox win64-0.5.0

### ISSUE THREAD

**Issue by esce76** [GrayHatter/uTox#149]
after update to 0.5.0 on windows Vista x64 utox is unusable :-( crashes instantly after run

**Comment by GrayHatter** [comment]
Can you start it with cmd.exe, or powershell, and give me the output?

Or find me on irc://irc.freenode.net/tox so that I can work this out?

Also can you try https://build.tox.chat/job/uTox_build_windows_x86-64_debug/ and see if that fails too?

Can you md5sum or sha256 sum the utox exe?

**Comment by GrayHatter** [comment]
should be fixed in df5e744 let me know if you can get this to work

**Comment by esce76** [comment]
hi ! thanx! utox_runner get the 0.5.1 binary and works like a charm :)
Regards!
