### ISSUE TITLE
AltGr+number must not switch tab

### ISSUE THREAD

**Issue by rvalles** [GrayHatter/uTox#157]
AltGr+number row is used in many keymaps (including the spanish keymap) to type relatively common symbols such as @,~,#,€,¬.

Therefore, AltGr+number must not switch tab.

**Comment by GrayHatter** [comment]
whoops... @stal @Doom032

**Comment by GrayHatter** [comment]
#47

**Comment by stal888** [comment]
cocoa uses the ctrl key, so we're good there.

I think there's only one AltGr key on normal keyboards, so you could exclude that one from the mask @GrayHatter

**Comment by Doom032** [comment]
@rvalles You're on Windows? Because I don't have this problem on Linux.

If so, @GrayHatter looking at the Windows documentation, the fix is probably to replace VK_MENU with VK_LMENU in windows/main.c:1612. I had expected VK_MENU to only match true on the actual Alt key, not Altgr, but I guess I was mistaken. I can't test on Windows though, so you may put in the fix.

**Comment by rvalles** [comment]
@Doom032: Issue doesn't happen with Linux indeed. Only Windows.

**Comment by rvalles** [comment]
This (altgr+number on Windows) is still an issue as of 0.6.1, which I've just upgraded to.

**Comment by GrayHatter** [comment]
can't reproduce this...

Are you sure you're on v0.6.1?

Where'd you get it?

Is it still affected?

**Comment by rvalles** [comment]
Yes, I can reproduce it. AltGr + Number row changes tabs.

* Windows 10.
* Happens with Catalan, Spanish, Irish input languages. Doesn't happen with Japanese (which is a bit special to begin with).
* 0.6.1 was obtained via the bundled updater.

**Comment by rvalles** [comment]
Furthermore (despite 0.6.1 in title bar), I've just done this test:

* Deleted utox (Roaming/uTox)
* Redownloaded and ran utox runner.

Issue persists.

**Comment by GrayHatter** [comment]
can you compile utox?

**Comment by rvalles** [comment]
Got VS2015, but haven't messed with mingw (which build seems to require) for a very long time; I'd have to look into it.

Do you think the version available via utox_runner wasn't really built from 0.6.1?

Let me know if you _really_ want me to try and build it.

**Comment by GrayHatter** [comment]
I was thinking about adding some more debug info so that I could see what
button is really getting pressed. Because that really shouldn't be happening

**Comment by GrayHatter** [comment]
can you check what key is being pressed http://www.keyboardtester.com/

**Comment by rvalles** [comment]
Notes:
To test numeric keypad be sure Num Lock is ON.
**Tester cannot differentiate between duplicate keys (Shift, Ctrl, Alt, Enter).** Be sure to test both of each.

**Comment by GrayHatter** [comment]
is it reading alt and ctrl correctly?

**Comment by rvalles** [comment]
alt and ctrl are as expected. AltGr seems to be read as control+alt. As far as I can tell, pressing control+alt lets me type |@# like pressing AltGr. (and switches tabs in utox all the same...)

**Comment by GrayHatter** [comment]
interesting... okay I think I can fix that

**Comment by GrayHatter** [comment]
@rvalles pushed a new commit to develop, let me know if that fixes it for you

or if you need me to build you an .exe

**Comment by rvalles** [comment]
I'll give building utox a try.

**Comment by rvalles** [comment]
This seems dead: https://jenkins.libtoxcore.so/

Where is it to grab the dependency libraries these days?

**Comment by tsudoko** [comment]
https://build.tox.chat/

**Comment by GrayHatter** [comment]
https://build.tox.chat/job/uTox-nightly_build_windows_x86-64_debug/

**Comment by rvalles** [comment]
After being disappointed as mingw/msys2 (as painful as I remember it), I tried your nightly build.

Now altgr doesn't switch tabs and allows typing |@# just fine, but alt does not switch tabs :/

**Comment by GrayHatter** [comment]
Alt was never supposed to switch tabs. Try crtl

**Comment by rvalles** [comment]
ctrl works, of course.

I recall alt works to switch tabs on Linux, without the altgr issue.
