### ISSUE TITLE
uTox package in Debian Jessie repo - gone

### ISSUE THREAD

**Issue by i-am-user** [GrayHatter/uTox#161]
using this HowTo, redirected from tox.org:
https://wiki.tox.chat/binaries#gnulinux
utox is gone, theres only qtox and toxic 
Can I expect it back?

**Comment by GrayHatter** [comment]
@stal888 @optimumtact @zer0-one

**Comment by optimumtact** [comment]
utox has never been packaged via pbuilder for release into a distro specific components

You must use the generic release component if you want to get a utox package, or use the community provided packages for jessie https://build.opensuse.org/package/show/home:antonbatenev:tox/utox

Can you confirm exactly which component you have configured in your tox.list source?

**Comment by i-am-user** [comment]
I'm using:
deb https://pkg.tox.chat/debian nightly jessie

**Comment by optimumtact** [comment]
Yes, unfortunately we do not have a utox package for the specific distro.

If you change it to nightly release - you will get a utox package, otherwise as mentioned you can use the community build (debian package available)

Apologies

**Comment by i-am-user** [comment]
thanks
