### ISSUE TITLE
sending a screen capture from utox to utox does not ask for acceptance

### ISSUE THREAD

**Issue by cebe** [GrayHatter/uTox#174]
starting two instances of utox and sending a screencapture.
The receiver does not need to accept it, it is sent right away and displayed.

Normal file transfer asks first.

Happens on latest develop on linux.

**Comment by DeerSpotter** [comment]
Happens on windows too. But I do like it the way it is. It makes it feel quick. I wouldn't mind the option of accepting the crop and then sending it to the client. But I feel like it could be more work for you guys.

**Comment by GrayHatter** [comment]
@cebe this is intended. Might be able to disable this per friend when friend settings are available
