### ISSUE TITLE
Client Crashing Resets all Settings to Default on next Start (WIN-10)

### ISSUE THREAD

**Issue by DeerSpotter** [GrayHatter/uTox#175]
When the UTOX client crashes for unkown reasons (#1) when i start it again i have to set all my options again (logging enabled, minimize to start tray, etc all the ones that are no's i said yes to) they revert to default after crashes and this gets annoying. Anyway to keep that from happening? Any local configs we can modify? 

1. most crashes were do to the fact i was removing a group that i didnt start from my list.

**Comment by GrayHatter** [comment]
@DeerSpotter when you have everything set correctly, close, and then reopen µTox that will make it save your settings.

Also, what makes it crash so often?

**Comment by GrayHatter** [comment]
this should be fixed in v0.7.1
