### ISSUE TITLE
WebRTC built into uTOX

### ISSUE THREAD

**Issue by DeerSpotter** [GrayHatter/uTox#176]
I love the fact the WebRTC is peer to peer already. You can stream 1080p instantly with no lag and have mouse tracking. 

I'm looking into how to make it work with this client. Anybody here working on something similar? Skype uses WebRTC I believe. It is really quick.

**Comment by GrayHatter** [comment]
@DeerSpotter this is probably a better issue to open on the toxcore repo

**Comment by GrayHatter** [comment]
upstream
