### ISSUE TITLE
uTox re-encodes PNG files when setting an avatar

### ISSUE THREAD

**Issue by tsudoko** [GrayHatter/uTox#179]
It makes uTox treat [my avatar](https://my.mixtape.moe/lwtyad.png) as too large, even though the size is lower than the max size.

**Comment by GrayHatter** [comment]
broken with #165

**Comment by GrayHatter** [comment]
@tsudoko if the fix in the new branch doesn't work, I need size on disk, and the size returned by size in gtk.c:164

**Comment by tsudoko** [comment]
Size on disk: 49295
Size when loaded: 157905

**Comment by GrayHatter** [comment]
@tsudoko probably not fixed in develop but I just updated the STBI headers

**Comment by GrayHatter** [comment]
@tsudoko should be fixed now. Please confirm?

**Comment by tsudoko** [comment]
Yeah, it's fixed
