### ISSUE TITLE
Scale cursor with DPI

### ISSUE THREAD

**Issue by benwaffle** [GrayHatter/uTox#18]

**Comment by GrayHatter** [comment]
Cursor is covered by the OS, how critical is this to you? There might be a way to supply our own cursor, but that seems unnecessary to me.

**Comment by benwaffle** [comment]
It's pretty useful, do you know how much work it would be?
GTK and Qt apps do this

**Comment by Doom032** [comment]
@benwaffle Do you mean the mouse cursor would have a different size when it is inside the µTox window? What would be the use of this? I'd assume if you used a different DPI, you'd like to change the cursor size in your OS anyway.

**Comment by benwaffle** [comment]
currently, GTK apps have a normal size cursor and utox has a half-size cursor

**Comment by cebe** [comment]
@benwaffle this is not the case for me on Gnome3, which desktop env are you using.

**Comment by benwaffle** [comment]
GNOME3

**Comment by benwaffle** [comment]
Do you have a HiDPI screen?

**Comment by benwaffle** [comment]
hmm, it seems to be scaled now
