### ISSUE TITLE
Oops! No encryption.

### ISSUE THREAD

**Issue by gity-up** [GrayHatter/uTox#184]
Been using utox for about 2 years. Always thought my sessions and conversations were encrypted. Trusted & bragged about this open source software and it's security features all the time. I ran the binary in a terminal for the first time ever, tonight. This is what I saw:

WARNING UTOX WAS UNABLE TO ENCRYPT DATA!
		DATA WRITTEN IN CLEAR TEXT!

No worries, I know the software is still in Alpha and it's free to use. My only 2 questions are:

Is this an erroneous message?

Is there anything I can try to get the encryption to work?

**Comment by GrayHatter** [comment]
@gitinwhereufitin yeah, I was operating under the assumption that no one used the terminal. There's already a fix for that merged into develop.

**Comment by gitinwhereufitin** [comment]
So... I pull binaries from here: https://wiki.tox.chat/binaries#gnulinux. Currently running utox Alpha 0.5.0 (Jenkins nightly)

Does your reply mean there is an uncommitted fix still being developed? OR has the fix been implemented in another binary that I can download from somewhere else?

**Comment by stal888** [comment]
That doesn't mean your messages are unencrypted, they always have and always will be.

It just means uTox is storing your private key unencrypted on disk because you didn't set a password in settings (this was the default behaviour before profile encryption was added).

**Comment by GrayHatter** [comment]
I'm sorry @gitinwhereufitin I misunderstood your post. @stal888 is correct; data is ALWAYS encrypted friend to friend. That warning is only about your profile, and warns that µTox doesn't have a password that it can use.

You can safely ignore it, it's only about your save file, and the warning will go away in the next version when there's no password entered.

**Comment by gitinwhereufitin** [comment]
Thanks to both of you for replying.

1.) So my video chats have and always will be encrypted over the Internet, right?

2.) My computer uses LUKS full disk encryption. The profile password would then just be an extra layer of security if my computer or computer user account were compromised, correct?

3.) Any other reason/benefit for me to set a profile password?

Great to hear the warning will be repressed/eliminated in the next version.

Sidebar: Is GrayHatter also Jenkins (nightly)?

**Comment by cebe** [comment]
> 1.) So my video chats have and always will be encrypted over the Internet, right?

yes.

> 2.) My computer uses LUKS full disk encryption. The profile password would then just be an extra layer of security if my computer or computer user account were compromised, correct?

correct.

**Comment by GrayHatter** [comment]
Everything on jenkins is from my repo, only one build is set up using the develop branch (windows x64), most of them are from stable master branch.

**Comment by gity-up** [comment]
Thank you everyone.

The response time in this repo is not human, it's simply amazing. The succinct and unequivocal answers are something wonderful too. It's like the workplace I've always dreamed of.

I'll close up the shop.
