### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by bivol** [GrayHatter/uTox#186]
Anti-malware app id-ed a uTox connection as malicious.

The uTox Win client doesn’t:

1) inter-session-remember "network" settings (like, minimize to system
tray). It's really annoying to have to re-set these after each boot

2) use a standard interface for drop-down boxes for the "network"
settings; you click on something, and the options which appear don't
"persist" unless you hold your clicked mouse button down (I know the
designers think they're doing something really rad by being different, but
it's not rad; it's wrong)

3) inter-session-remember your "profile password." I'm sure this is by
design, but it's dumb; it means people simply won't use it. And, sure,
security's great and all, but if no one uses it, then no one has that
waunted security. :-)

**Comment by Impyy** [comment]
1) Not sure what you mean by this.

2) If you don't like non-standard UI toolkits I suggest you switch to qTox.

3) It's not dumb. Remembering the password is dumb as it defeats the entire purpose of encrypting the profile. If you really don't like entering your password every time you start uTox, you should just leave it empty.

**Comment by GrayHatter** [comment]
Your malware app is broken. I'd submit an issue with them, but you never said which one.

1) Settings should be save, which ones aren't? What OS? What version of µTox? Are you sure your permissions.

2) There's an open issue for that, and fixing that is already on the roadmap, it's just way at the bottom. (Also, I like it that way better, so I think it is super rad; and that you're wrong)

3) No! @Impyy is correct, just leave the password box empty, and it wont encrypt your profile.

**Comment by GrayHatter** [comment]
stale, let me know if you still see these issues...
