### ISSUE TITLE
TOX ID disappears in windows

### ISSUE THREAD

**Issue by ingvar1995** [GrayHatter/uTox#187]
![image](https://cloud.githubusercontent.com/assets/10050680/12587459/8bf4b3ec-c465-11e5-8501-f33dd937ca00.png)
Tox id sometimes disappears in windows. And cannot be copied. when tox starts it save tox id in self.id_buffer and write it to debug. but later smth happens and self.id_buffer becomes empty string. memory trouble?

**Comment by GrayHatter** [comment]
What version of uTox and windows?

**Comment by ingvar1995** [comment]
win 7 x64 0.5.1

**Comment by GrayHatter** [comment]
Can you make it happen on demand?

**Comment by ingvar1995** [comment]
no.

**Comment by GrayHatter** [comment]
I'm aware, let me know if it ever happens again

**Comment by ingvar1995** [comment]
it happens often during first utox start, I think.

**Comment by GrayHatter** [comment]
Play around with it, and see if you can predict when it will happen. Do you make a lot of calls?

**Comment by GrayHatter** [comment]
Might be related to how uTox starts up toxcore now

**Comment by ingvar1995** [comment]
i can't predict it unfortunately. no idea. but sometimes it can happens 2 in a row

**Comment by GrayHatter** [comment]
Encrypted profile?

Does it display and disappear, or never shows?

Where'd you get your exe?

**Comment by ingvar1995** [comment]
1) no
2) never shows. but sometimes I can see short part of ID
3) I get updates using utoxrunner. but in my own builds I have same problem
I will try to find this bug but I want to improve screenshots first. that's not critical bug

**Comment by GrayHatter** [comment]
if part of the toxid disappears, it's a memory issue. and it's that's bad

If you can compile it with clang and asan, it'll tell you exactly where it's going arry if it's a memory bug

**Comment by GrayHatter** [comment]
I've never seen it, so I can't duplicate it

**Comment by ingvar1995** [comment]
looks like bug here (tox.c):
`if (init_avatar(&self.avatar, hex_id, avatar_data, &avatar_size)) {
        self.avatar_data = malloc(avatar_size);
        if (self.avatar_data) {
            memcpy(self.avatar_data, avatar_data, avatar_size);
            self.avatar_size = avatar_size;
            self.avatar_format = UTOX_AVATAR_FORMAT_PNG;
            char_t hash_string[TOX_HASH_LENGTH * 2];
            hash_to_string(hash_string, self.avatar.hash);
            debug("Tox Avatar Hash: %.*s\n", (int)sizeof(hash_string), hash_string);
        }
    }`

**Comment by GrayHatter** [comment]
what part? and why can't I duplicate it?

**Comment by NiceMemeBoi** [comment]
Can Confirm, The box where the Tox ID should be is empty
![89118252681a2d72338c5b684e6986e7](https://cloud.githubusercontent.com/assets/16965489/12689440/cdbbedf6-c6d4-11e5-81ee-bbe069133640.png)

**Comment by GrayHatter** [comment]
if you know git bisect cant you find the breaking commit?

**Comment by NiceMemeBoi** [comment]
Just a sec

**Comment by ingvar1995** [comment]
I think I found breaking commit.
