### ISSUE TITLE
No ringtone?

### ISSUE THREAD

**Issue by jf99** [GrayHatter/uTox#189]
There used to be a ringtone in uTox 0.3.2. It seems to be gone in newer versions. (Yes, I have enabled it in the settings.) Please re-add it.

**Comment by GrayHatter** [comment]
theres' still a ringtone, there was a bug that sometimes affected the ringtone in 0.5.0, but it's fixed in 0.5.1. If you're already on 0.5.1, reopen this issue, otherwise, you need to upgrade.

**Comment by cebe** [comment]
I never had a ringtone when playing with calls in utox... also not on the latest develop.

**Comment by v2e** [comment]
I can confirm that there are no ringtone and pup-up notification after upgrading from 0.4.x to the current git (commit e137eb8f7504fb304e678b71fc2e197bfd9104a0)

**Comment by jf99** [comment]
It's not fixed in 0.5.1. How can I re-open the issue?

**Comment by GrayHatter** [comment]
fixed in #196
