### ISSUE TITLE
profile seg fault after update

### ISSUE THREAD

**Issue by thedanish** [GrayHatter/uTox#197]
My profile (unencrypted) causes tox to crash after a recent update. Some stuff about lacking metadata, not sure its' relevant. then:
uTox:	Connected to DHT!
Segmentation fault

Deleting the profile and getting a new one works fine, but I lose all my contacts.

Sorry I don't have a more concrete error. Happy to put a little work in if anyone has any ideas? Is there a way to perhaps edit the profile? The only thing I could suspect is a friend who changed their name to nothing, which sometimes caused some odd issues when they logged in.

**Comment by GrayHatter** [comment]
OS? Version?

uTox version?

Source your uTox?

Do you still have a copy of your tox profile?

**Comment by thedanish** [comment]
Apologies.
Debian Jessie amd64
uTox version - 0.5.0-7e29074-81
deb pkg.tox.chat/debian nightly

I do still have a copy of the tox profile and am happy to send it to you, but due to the potentially private nature of it I would prefer not to attach it to this message. Is there another method I could perhaps send you the file?

**Comment by GrayHatter** [comment]
That's a very good idea. If you're willing to do a little debugging, you
would never have to send me your Tox profile. Otherwise we can transfer the
file via Tox?

Also, you're abut out of date. 0.5.1 is the current version, I don't think
it'll make your profile work but it's worth a shot.

**Comment by thedanish** [comment]
Let's do both.

5CE2C6A2ADC87A63CA3B7E2F91C837A39CE778327582911A734732EA775D6149FED0BA484CF8

I will see if I can get the 0.5.1 update also.

**Comment by GrayHatter** [comment]
@thedanish I'm going to be working on this today, 

this is me : 6B1CA5A499DF52F99B74778CDE1FCB0A26A6A96644BA18DC92D1373CA84692296DB05F88826F

**Comment by GrayHatter** [comment]
had to change profiles...

**Comment by GrayHatter** [comment]
I'm pretty sure this is fixed
