### ISSUE TITLE
DPI setting ignored at start

### ISSUE THREAD

**Issue by sylware** [GrayHatter/uTox#199]
In recent utox, the DPI is ignored at the start of the program. Have to set it manually each time I start utox.

**Comment by GrayHatter** [comment]
What version of µTox are you using?

**Comment by sylware** [comment]
Updated for linux x86_64 2 days ago from a months old build.

**Comment by dcapeletti** [comment]
DPI ignored loading. UTOX version 0.5.1 installed a few minutes ago.

**Comment by sylware** [comment]
fixed in recent µtox
