### ISSUE TITLE
Adding friends/switching to settings requires too many clicks

### ISSUE THREAD

**Issue by tsudoko** [GrayHatter/uTox#20]
Subjective, the additional button makes the whole operation feel too slow for me.

**Comment by GrayHatter** [comment]
@tsudoko I agree, it's swapped already, let me know if you think the button should just die?

**Comment by tsudoko** [comment]
Sort of fixed in ui-rev3

**Comment by GrayHatter** [comment]
leaving open until we check length, and add on a single click

**Comment by stal888** [comment]
It doesn't feel right pasting a tox id into that tiny text field

**Comment by GrayHatter** [comment]
thoughts?

**Comment by stal888** [comment]
Try making it expand? Or make the + button pop up a modal panel?

**Comment by GrayHatter** [comment]
I few extra ideas, 

* at the very least [return] needs to do something
* right click could add (paste and quick add friend) (paste and quick add group [for pending group chats])
* expand over and right on text entry
* mouse over could expand a to a 2nd button
* toxids pasted in could be auto added

**Comment by GrayHatter** [comment]
done
