### ISSUE TITLE
uTox tox save reverting to a version from months back

### ISSUE THREAD

**Issue by DexterMcKinnery** [GrayHatter/uTox#202]
Hey! I had a quick browse and I didn't see this listed yet anywhere...

This has happened to both me and my friend now. We've restarted Tox/opened it for the first time in the day to find that our profiles, whilst still the same ID, are reverted to a state that they haven't been in for months! Old contacts that were deleted are now back, new ones that were added are now gone, people's names are now what they were months ago, same with their status messages and mine.

I'm on Windows 7, 64 bit, uTox 0.5.1. Pretty sure my friend is the same though she MIGHT be using 32 bit.

It is literally calling up an ancient version of the tox save from somewhere, goodness knows how, replacing the current save with the old one. Luckily I had my tox saves on my desktop from when I was trying to fix a different bug... but I doubt others will be so lucky.

Speaking of which, that other bug was a "ghost" transfer that kept persisting every time I or she came online. Had to delete a file in the Tox application data to get this to vanish. The error occurred when she fell offline mid transfer. The transfer would then try and send again every time our clients reconnected because the file that tells Tox to do that wasn't being deleted when the transfer was accepted or declined. Probably an easier thing to fix!

**Comment by ingvar1995** [comment]
I can confirm. it's win only bug, close to #188 Should be fixed ASAP

**Comment by GrayHatter** [comment]
should be fixed already
