### ISSUE TITLE
message notifications no longer work on linux

### ISSUE THREAD

**Issue by jf99** [GrayHatter/uTox#205]
Since uTox 0.5.1 I no longer get a notification when someone writes me a message. Also, when I have the uTox window minimized (but not to tray), it doesn't start blinking when there is a new message.

My desktop environment is Cinnamon 2.8.6 on Arch linux.

**Comment by v2e** [comment]
I am not sure if this is the same issue or not, but there is no notification about the new message or about the incoming call with the 0.6.0 version (commit bb1f1c655eb7d3276ab4e292f2cc483632a540be). It did not also work in 0.5.1, but it worked fine in 0.4.4, for example.

**Comment by cebe** [comment]
confirmed.

**Comment by cebe** [comment]
$ git bisect bad
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
7cf34e91293ea1f83e708eb9aa63812f250cc305
2dabdcc6a1649a7d527616b4ef39bca9c92da3a0
7e1079db844d30bf2349f228f8c699b245c7b50d
d552d40d44827bcd73e93ba0feef14f35841989d
We cannot bisect more!

**Comment by xaizek** [comment]
I'd expect this to be fixed by now, but I didn't get notifications with v0.9.1 and I don't get them with v0.9.4 either (only sound notifications). So, not fixed then?

**Comment by GrayHatter** [comment]
It's working for me and others.

Do you have dbus installed and working? Are you getting other notifications
from different apps?

**Comment by xaizek** [comment]
> Do you have dbus installed and working? Are you getting other notifications from different apps?

I think so, because notifications are working with utox v0.5.0, `notify-send` works, skype is able to send notifications via dbus too.

**Comment by GrayHatter** [comment]
What distro are you running? Where did you get your version of uTox

**Comment by xaizek** [comment]
> What distro are you running?

Slackware current (almost, not all packages are up to date), 64-bit. Just updated dbus from 1.10.6 to 1.10.8, not sure it will make any difference.

> Where did you get your version of uTox?

[Buildbot output](https://build.tox.chat/view/Clients/job/uTox_build_linux_x86-64_release/lastSuccessfulBuild/artifact/utox_linux_x86-64.tar.xz) from the [wiki](https://wiki.tox.chat/binaries#other_linux).

**Comment by GrayHatter** [comment]
The builds on build.tox.chat are made without dbus support. 

You can switch to the nightlies, I'll enable dbus in those builds

**Comment by GrayHatter** [comment]
https://build.tox.chat/view/uTox/job/uTox-nightly_build_linux_x86-64_debug/

**Comment by xaizek** [comment]
> You can switch to the nightlies, I'll enable dbus in those builds

This one works, thanks.

> The builds on build.tox.chat are made without dbus support.

I thought this might be the case, but decided that dbus support is enabled, because there is a direct dependency on it:
```
$ readelf -d `which utox` | grep dbus
 0x0000000000000001 (NEEDED)             Shared library: [libdbus-1.so.3]
```
You might want to remove this dependency or just enable dbus support as anyone using those builds must have dbus installed in order to run that build anyway.
