### ISSUE TITLE
when got a message, uTox has no tip audio, how to fix?

### ISSUE THREAD

**Issue by HarlockHomes** [GrayHatter/uTox#207]
uTox has only tip message on the right below, but no audio.

but uTox on other PC, it can play a wave, how to fix?

**Comment by GrayHatter** [comment]
I don't understand the issue, 

I'm going to need a lot more information

**Comment by HarlockHomes** [comment]
When you receive a txt message. Emit a beep sounds.
In the Windows 10 in the case.
But in Windows 8.1, no sound will ring. how to fix?

**Comment by GrayHatter** [comment]
Do you get alert beeps with other applications?

Is µTox in the foreground, or the background? µTox only beeps when in the background.

**Comment by HarlockHomes** [comment]
what other App?
right, it's in the background.
what wav file is it use?

**Comment by redmanmale** [comment]
Same thing on Win 7 x64.

**Comment by GrayHatter** [comment]
@HarlockHomes 
Do ANY other applications beep?
There is no wave file, it's using the native sound
I'll look into it

@redmanmale are you getting any kind of notification?

**Comment by redmanmale** [comment]
Balloons are showing up when new message arrives.
And I tested headphones&mic using echo, it works just fine, I can hear myself speaking.

**Comment by GrayHatter** [comment]
closing in favor of #233
