### ISSUE TITLE
Can't accept calls: uTox:	Error trying to toxav_answer error (1)

### ISSUE THREAD

**Issue by aoaaxy** [GrayHatter/uTox#208]
```
Accept Call (video): 0 60
uTox:	Answering video call.
uTox:	Error trying to toxav_answer error (1)
Accept Call (video): 0 60
uTox:	Answering video call.
uTox:	Error trying to toxav_answer error (1)
Accept Call (video): 0 60
uTox:	Answering video call.
uTox:	Error trying to toxav_answer error (1)
```

Chat works though. But answering  audio-only or audio+video  calls  does not work(it's in permanent orange state). Ringing does work(sound is heard) but now due to this bug it's continous until exiting utox. Previously, when it worked for me, the ringing sound could not be heard at all but a/v answering worked. (**EDIT2:** this means that my prev. working version was prior to this commit which fixes ringing: https://github.com/GrayHatter/uTox/commit/f453a31a1c35ddc6ab2c22932c76d0fd79a14c4c )

This is on gentoo, with tox-overlay...  (**EDIT1:** that overlay is here https://github.com/Tox/gentoo-overlay-tox )
GIT update -->
   repository:               git://github.com/GrayHatter/uTox.git
   at the commit:            bb1f1c655eb7d3276ab4e292f2cc483632a540be

GIT update -->
   repository:               git://github.com/irungentoo/toxcore.git
   at the commit:            72b1a17cc28c9a5a653823336bf0a495f6f271b1

**EDIT1:** I checked: the above commits are latest at the time of this writing.

**Comment by aoaaxy** [comment]
At first glance, looks like the issue is here: https://github.com/GrayHatter/uTox/blob/8a37550d3318f403a18b204e51df99bc5a6712b6/src/tox.c#L1147
Should check `ans_error` instead?

**Comment by GrayHatter** [comment]
this might be fixed in current the develop branch.

But there's a few issues with the webcam not closing correctly, so this likely won't be fixed until I get that worked out.

**Comment by aoaaxy** [comment]
Thanks. Would you please fix the `ans_error` one also: https://github.com/GrayHatter/uTox/blob/master/src/tox.c#L1147
I can't test yet, until 2 days from now. But I'll try to get Gentoo inside VirtualBox to get another utox instance to test sooner; will let you know if it's fixed for me.

**Comment by aoaaxy** [comment]
I tested audio call only(well, I tested webcam too but same thing):

```
Friend-0 Typing:	0
FileTransfer:	Friend (0) has canceled file (0)
A/V Invite (0)
uTox AV:	call friend (0) state for incoming call: 20
starting ringtone!
Friend-0 Typing:	1
Accept Call: 0
uTox:	Answering audio call.
Accept Call: 0
uTox:	Answering audio call.
uTox:	Error trying to toxav_answer2 error (1)
Accept Call: 0
uTox:	Answering audio call.
uTox:	Error trying to toxav_answer2 error (1)
Friend-0 Typing:	0
Accept Call: 0
uTox:	Answering audio call.
uTox:	Error trying to toxav_answer2 error (1)
Accept Call: 0
uTox:	Answering audio call.
uTox:	Error trying to toxav_answer2 error (1)
```

The first time I press to answer, I get this

```
uTox:   Answering audio call.
```

But it keeps ringing and it's still yellow button.
The subsequent times I press to answer, the yellow button and ringing remain unchanged but the message is different:

```
uTox:	Answering audio call.
uTox:	Error trying to toxav_answer2 error (1)
```
`toxav_answer2`  is a modification to see which one was triggered and this this one: https://github.com/GrayHatter/uTox/blob/master/src/tox.c#L1193

utox commit d1852503a0b1040b95c22d1bb76779fbb53dd769
tox commit 72b1a17cc28c9a5a653823336bf0a495f6f271b1

**Comment by GrayHatter** [comment]
fixed in develop

**Comment by aoaaxy** [comment]
I am still not able to answer calls; commit tested: ccd18fcea58f61f7c55eb580e8ee1edab0b36658
```
uTox AV:	call friend (0) state for incoming call: 60
starting ringtone!
Accept Call (video): 0 60
uTox:	Answering video call.
Accept Call (video): 0 60
uTox:	Answering video call.
uTox:	Error trying to toxav_answer2 error (1)
Accept Call: 0
uTox:	Answering audio call.
uTox:	Error trying to toxav_answer2 error (1)
```

I am switching to the working commits now, therefore I won't be able to test if this is fixed anymore.
utox commit b623d58
tox commit 61f8e65c0157049ac26bf9b081ba6842d7defdeb
I'm closing this issue because of that. 
But if anyone else encounters this issue, I guess they can re-open or make a new issue, otherwise, you can safely assume this issue only impacts me.
