### ISSUE TITLE
Password "show" button has wrong tooltip

### ISSUE THREAD

**Issue by cebe** [GrayHatter/uTox#209]
![bildschirmfoto von 2016-02-22 10 14 43](https://cloud.githubusercontent.com/assets/189796/13214005/32512f30-d94d-11e5-9238-9f7b1ac1babe.png)

**Comment by GrayHatter** [comment]
whoopsies! Good catch, thanks.

Is that the actual alignment? It shouldn't be that far off. What DPI are you on?

**Comment by cebe** [comment]
I'm at DPI "Normal (100%)" but it is similarily wrong aligned on other DPIs.
