### ISSUE TITLE
Unable to select avatar in linux client

### ISSUE THREAD

**Issue by utoxxer** [GrayHatter/uTox#215]
The avatar file browser window shows only directories. No images are visible in the directories being browsed.

GTK versions:
libgtk-3-0       3.14.5-1
libgtk2.0-0     2.24.25-3

**Comment by GrayHatter** [comment]
@benwaffle

**Comment by cebe** [comment]
same here. Selector for sending files works fine though.

Related issue: the dialog for saving received files has the title "Select Avatar"

**Comment by GrayHatter** [comment]
fixed in develop

**Comment by cebe** [comment]
> Related issue: the dialog for saving received files has the title "Select Avatar"

this is still not fixed, opened a PR: #220
