### ISSUE TITLE
Problem to close the preview camera

### ISSUE THREAD

**Issue by dcapeletti** [GrayHatter/uTox#218]
I had problems when the camera preview is closed. UTOX version 0.5.1 just downloaded.
--------------------------------
Video size: 640 480
start webcam
started video
new window 0
Video size: 640 480
VIDIOC_REQBUFS error 16, Dispositivo o recurso ocupado
video_init() failed
uToxVID:	Changed video input device
stop webcam
VIDIOC_STREAMOFF error 9, Descriptor de archivo erróneo
*** Error in `./utox': munmap_chunk(): invalid pointer: 0x00007f48a40070cc ***
Abortado
---------------------------------

**Comment by GrayHatter** [comment]
@dcapeletti version 6.1 is now in master, ping me if you still have any issues.
