### ISSUE TITLE
Can not cancel any call

### ISSUE THREAD

**Issue by cebe** [GrayHatter/uTox#222]
[this](https://github.com/GrayHatter/uTox/issues/221#issuecomment-189999169) does not seem to be related to the video preview bug.

If I start a call with someone, I am not able to cancel it. Any time I press the call button it will print the message that a new call was started, nothing else happens.

**Comment by cebe** [comment]
git bisect:

55d170266816837568ba69661ced5a1c4f95be0f is the first bad commit

**Comment by cebe** [comment]
reading the changes, I have no idea however how it could be related...

**Comment by GrayHatter** [comment]
yeah... are you sure thats the first bad commit?

**Comment by cebe** [comment]
I did a `git bisect start v0.6.0 v0.5.0`, ran `make` after each checkout and declared the parts with `git bisect good`/`git bisect bad` and that is what it gave me, no idea what is going on...

**Comment by cebe** [comment]
trying a second one. There are a lot of commits in this repo at a state that does not compile which makes it really hard to run a bisect.... :-/

**Comment by cebe** [comment]
This is what I came up with now:

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 91f91c439dd55dbd3856f0f855508edf9f63c79e
> d781d303cdd7431ec7a0f630b7dc19e012d267fb
> 502763b2e4ef5759276b89415fe6d55c51ff2fa6
> de2f9d3c849e33d2f33f05205a8a1905da87bf52
> 1d1bf6393fe41da564d005cedb687c02388a8c37
> b9478d70e43832919eb6eedf4e8a93253b866cf3
> 54902994a9ac2cd1daf678fc2512a5e7fa274584
> bfa18335ab49087f080aa53ab83e30d60abab664
> 9077108fabd854f92fead5c4678fe6b031f05fa5
> We cannot bisect more!

**Comment by GrayHatter** [comment]
@cebe is this fixed in develop?

**Comment by cebe** [comment]
yep, works and I even hear a ring tone for the first time :-D

:+1:
