### ISSUE TITLE
utox hogs the first and current sound cards all the time

### ISSUE THREAD

**Issue by calimeroteknik** [GrayHatter/uTox#223]
I'm creating this here as a followup of https://github.com/notsecure/uTox/issues/845

>Right at startup, µTox takes a handle on the audio output device.
This has the effect that no other application can use the audio output or input, even when utox doesn't use them at all for anything.

This also increases power consumption (the sound card won't enter powersaving mode).

That's reproducible for instance on ALSA without dmix (dmix reduces sound quality, and some applications also need direct hardware access).

>I believe it would be excellent to open the audio device only when needed (conversation, and maybe sound notifications if any), and close them afterwards.

I'll note that utox also still hogs the first soundcard even if I select a different sound card (so it would hog that other soundcard instead, that was my fix with 0.5).
This particular point looks like a new bug.
utox doesn't stay stuck if I deny it access to my sound card now, though, so I use that workaround.

**Comment by Anubis-the-god-of-whatever** [comment]
Might be connected the same issue - uTox win8 64 bit uTox alpha 0.7.1 - when uTox is open, my web video (well, youtube:) sound is massively decreased (both in max volume and in quality). I don't think it impacts video playback in apps (vlc). IT returns to normal as soon as you close uTox. Tried muting it via volume mixer, tried disabling audio on uTox - nothing helps, could not find any work around on the web.

**Comment by tsudoko** [comment]
@Anubis-the-god-of-whatever 
It might be due to win8 treating uTox as a communication app, IIRC there is a switch in sound settings for disabling auto-decreasing.

**Comment by Anubis-the-god-of-whatever** [comment]
disabled. no impact. But thanks have missed this in my previous tests.

**Comment by GrayHatter** [comment]
@Anubis-the-god-of-whatever uTox does hold an audio handle to play the ring tone, this can cause these symptoms. But if you disabled that feature (and restart maybe?) and It's still happening, something else is wrong with your system.

It also could be that your audio driver is broken, and is downgrading everything while uTox is running (assuming that uTox tries to use a lower audio quality.)

If you can replicate this issue, on demand, you should open a new issue.

**Comment by Anubis-the-god-of-whatever** [comment]
@GrayHatter disabled ringtone, audio filtering microphone, even selected speakers as my audio output device (it appears when I'm with my headphones it seems), restarted uTox (have not rebooted the PC though) - didn't helped. Tried updating drivers over standard windows driver utility - found nothing to update. And I fully agree it might be my laptop issue (it's a corporate laptop full of corporate spyware and gods know what else:) - the only strange thing about this issue that keeps me thinking this might be a issue with uTox - when the video is playing with audio, and I open the windows volume mixer - it shows audio being played on 'device' (headphones or speakers), firefox _and_ uTox, but not on any other of the applications (which include 2 other messengers - skype for business and sametime). And If I mute uTox, it does not help, however if I close uTox and open again - another uTox appears on the sound mixer, unmuted, next to a muted one.
Just double checked - this is not just an issue with web video or audio - same thing with local files, both video and audio.

**Comment by calimeroteknik** [comment]
@GrayHatter reporting after reading this https://github.com/notsecure/uTox/issues/845#issuecomment-214075511

Testing with branch master on 1bc1209 (=v0.8.1), and with branch develop on c38fcfe, same results:
The handle on the selected sound card is always open. If the default soundcard is available at startup, it is hogged too.

In other words, the current situation is still the one described in the first message of this issue.

**Comment by GrayHatter** [comment]
I should have this fixed at least for start up.

If anyone could test this out, and tell me that uTox doesn't hold a lock on the sound card. I'll put some more time into better logic for opening and closing it as needed.

**Comment by fcore117** [comment]
if you could fix jenkins nightly, i could test and if needed even with debugger logs?

**Comment by GrayHatter** [comment]
it's fixed now

**Comment by calimeroteknik** [comment]
Yes, only the selected sound card is hogged now!

utox still tries to open the first audio output at startup, it seems.
When my first sound card is already in use (which is not the card utox is configured to use), I get this:
`AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': device or resource busy`
This doesn't cause any issue in itself.

However, I'm getting related segfaults (not every time, when in GDB).
Here the first run doesn't segfault, but the second does (it's always in that function): [utox-segfault.txt](https://github.com/GrayHatter/uTox/files/256668/utox-segfault.txt)

**Comment by GrayHatter** [comment]
that should be fixed now too

**Comment by calimeroteknik** [comment]
Confirmed, the segfault doesn't happen anymore. ✔
So with this, the regression (first part of the title) is gone.

However @GrayHatter utox still keeps a handle on the currently selected audio output.
Effects: no other application can perform direct hardware access; and powersaving can't kick in.
