### ISSUE TITLE
DPI UI error in Win Vista x64

### ISSUE THREAD

**Issue by esce76** [GrayHatter/uTox#224]
On Vista x64 time-to-time on launch uTox the everything in UI was a very large (as U see on pic rel).
As always i go to Settings > User Interface > DPI i was able to set "normal", but not now. 
Strange >BUG PLEASE< on the DPI Settings :/

http://x3.cdn03.imgwykop.pl/c3201142/comment_86ATrFCvChPRzB1J5RtUWUdAHCxVHicZ.jpg

**Comment by esce76** [comment]
utox_save have only 16 bytes. Can i post content of utox_save here?

**Comment by GrayHatter** [comment]
Sure, just make sure it's a hex dump.

It's a binary save file

**Comment by redmanmale** [comment]
It also occurs on Win 8.1, x64.
![screenshot](https://puu.sh/nvE9x/a3f45c887a.png)

**Comment by esce76** [comment]
so here is hex content of utox_save :
02 01 01 00 30 02 F0 00
20 03 58 02 00 00 00 00

**Comment by deedend** [comment]
Same problem here, like redmanmale, on Windows 10 x64; how can I send you my utox_save?

**Comment by redmanmale** [comment]
In new version (0.7.0), bug is still here.

**Comment by esce76** [comment]
i confirm. After update interface is huge and still unusable on (my) Vista x64

**Comment by GrayHatter** [comment]
If you need a short term solution, you can delete utox_save and it should
come back to normal.

DO NOT DELETE tox_save.tox

**Comment by esce76** [comment]
nope. The solution dont work :/

**Comment by GrayHatter** [comment]
that shouldn't be a thing...

**Comment by redmanmale** [comment]
It's working for me just fine.

@esce76 Do you close uTox before deleteing utox_save? Otherwise solution won't work.

**Comment by esce76** [comment]
yes. i double checked it again. And surprisely new run of utox don't create this file... UI is still large, and cant change it

**Comment by esce76** [comment]
@redmanmale form what location in filesystem U run utox? (system partition and what path ? )

**Comment by redmanmale** [comment]
Default paths (correct me if I'm wrong, but we can't change them yet).
`utox_save` in `C:\Users\redmanmale\AppData\Roaming\Tox`
Executable `uTox.exe` in `C:\Users\redmanmale\AppData\Roaming\uTox`

**Comment by GrayHatter** [comment]
I can't duplicate this at all so I'm going to close it.

If you're still having this issue tag me and I'll look into it again.

If you can, I need a hexdump of your utox_save file as well.
