### ISSUE TITLE
Cross-compile script for Windows is outdated.

### ISSUE THREAD

**Issue by LER0ever** [GrayHatter/uTox#226]
The source code structure changed a lot since github.com/notsecure/uTox moved to here, but the cygwin compile script seems the same :( . Although utox passes the TravisCI build, the cygwin script for windows building is certainly outdated. Maybe someone should update the tools/cygwin-compile.sh?

**Comment by GrayHatter** [comment]
Yeah, that's because I updated the make file instead. If you set the CC to ming, make should just work. Let me know if you need any help. I'm not sure it'll working outside cygwin, but then neither would the script.

Let me know if you have any issues

**Comment by LER0ever** [comment]
Thank you! Makefile works perfectly for me. It generates x64 binary by default and I changed the toolchain to build 32bit binary. But maybe you can update the BUILD.md file.

**Comment by GrayHatter** [comment]
I write code, not documentation. But I'll add it to my list.

Pull requests welcome
