### ISSUE TITLE
utox.org v. tox.chat

### ISSUE THREAD

**Issue by gity-up** [GrayHatter/uTox#229]
I just discovered tox.chat while perusing this repo.

1. What are the differences between utox.org & tox.chat?

2. Are the binaries the same?

tanks mon'

**Comment by GrayHatter** [comment]
tox.chat binaries are made by build.tox.chat

utox.org binaries are made by @irungentoo

**Comment by gity-up** [comment]
Hmm... any reason why I might want to run one instead of the other if they both work?

1. Is one official and the other not?

2. Do they have different licensing?

3. Is one binary going to get upgrades more frequently?

**Comment by GrayHatter** [comment]
build.tox.chat are nightlies

the runner is always the most stable version
