### ISSUE TITLE
Video quality / compression

### ISSUE THREAD

**Issue by atgote** [GrayHatter/uTox#23]
[GrayHatter] >> AV scaling is optional in ToxAV, and then it's a client issue...

If so, I think it worth including this possibility in the uTox feature list...

[ADDED] Regarding new ToxAV API, maybe it will solve the issues described below... When it will be implemented in main branch? Is it possible to test it on windows machine for now? (I have no Windows toolchain / IDE installed)

I don't know if it is only my/my friends issues, but sometimes it is just impossible to view / read anything from the transmitted screencast.... Is it possible to solve this issue?

This is cast from linux x64 (3.10.17) to windows machine, uTox version 0.3.2: 
![image4153](https://cloud.githubusercontent.com/assets/3784291/10870670/f07fa702-80d8-11e5-9edd-446181e63d31.png)

This is from windows 7 x64 to linux machine:
![win-to-lin](https://cloud.githubusercontent.com/assets/3784291/10870672/f38653a6-80d8-11e5-98f4-f04f19494a3b.png)

**Comment by GrayHatter** [comment]
I'm going to leave this open because µTox doesn't change video bit rates yet, and it's something I'd like to do.

but for your issue specifically, have you tried the new ToxAV api branch?

find me in IRC and i can get you some test versions for Windows

**Comment by GrayHatter** [comment]
uTox uses adaptive bitrates now, there's a few open issues in core as to how it handles AV, but for now I'm going to close this one.
