### ISSUE TITLE
Error making call xlib (utox Alpha version 0.6.1)

### ISSUE THREAD

**Issue by gity-up** [GrayHatter/uTox#230]
This new binary is broken for me. I am no longer able to video or voice chat.

The call just rings on either end.
It doesn't matter who initiated it.
utox reports a call is being made but when answered, it just ends, however, the ringing continues (weird).

One computer runs xubuntu 14.04 x86

The other computer is running Windows 10 x64.
We're both running utox Alpha version 0.6.1

**Comment by GrayHatter** [comment]
try calling echo bot, tell me what happens

76518406F6A9F2217E8DC487CC783C25CC16A15EB36FF32E335A235342C48A39218F515C39A6

**Comment by gity-up** [comment]
OK, looks like I called myself. I get a 2nd window showing me what my web-cam sees. Very cool... but what does it all mean? dun dun dun! (:

Should I test it again with one of my friends or upload what gets reported when I run it from a terminal?

**Comment by GrayHatter** [comment]
Yes, terminal output would be helpful...

I'm aware of another issue that I'm going to be looking into soon.

**Comment by GrayHatter** [comment]
should be fixed, reopen or ping me if not

**Comment by gity-up** [comment]
Sorry for the long hiatus. Thank you, 0.7.0 put me back in business.
