### ISSUE TITLE
Beep on new message.

### ISSUE THREAD

**Issue by viruzx** [GrayHatter/uTox#233]
This is just a quality of a life feature that should be very easy to implement. Just a beep on new message.

**Comment by utoxxer** [comment]
Looking very forward to this one. In utox on linux with gtk environments, the panel/dock will flash to let you know you have a new message, but on qt desktops like KDE this is more faint and difficult to see. So it's hard to tell when a new message arrives.

**Comment by GrayHatter** [comment]
I'm still waiting for @irungentoo to share a copy of his C music code

**Comment by tr37ion** [comment]
How about bringing Ubuntu Touch message sounds to utox then? I really like utox and its dark theme. They are really nicely done.

**Comment by roranicus** [comment]
If such a feature goes in, please make it optional. The reason why I use uTox is that, unlike qTox, it doesn't make my taskbar flash or otherwise gets in my face with notifications. This needs to be something that can be easily disabled.

**Comment by GrayHatter** [comment]
see also #207

**Comment by GrayHatter** [comment]
in develop
