### ISSUE TITLE
1-pixel wide tray icon

### ISSUE THREAD

**Issue by strk** [GrayHatter/uTox#235]
The uTox tray icon is 1 pixel wide on my "Gnome Flashback" interface.
Uncommenting the debug call in src/xlib/main.c:475 gives me:
``
Tray size == 32 x 32
Tray size == 32 x 32
Tray size == 1 x 24
```

What would have changed the tray width ?

NOTE: happens both in master and develop (2a1a7ce56e1845a7346c8d3e8e3088d2d4e605fd) branches.

**Comment by strk** [comment]
Similar thing happened in the past with qtox, but unfortunately there's no pointer to an actual fix there: https://github.com/tux3/qTox/issues/1067

**Comment by cebe** [comment]
duplicate of #185 ?

**Comment by strk** [comment]
Definitely a duplicate of #185, yes
