### ISSUE TITLE
Scrolling with the mouse wheel is very slow

### ISSUE THREAD

**Issue by jf99** [GrayHatter/uTox#237]
On Arch Linux with uTox 0.6.1, I can only scroll about 1 line using the mouse wheel, without lifting my finger. A friend using windows 7 and uTox 0.5.1 reports the same issue.

**Comment by utoxxer** [comment]
Slow for me on linux too. I either use page up/down in the conversation window, or manually click and drag the scroll bar to the right of the conversation.

**Comment by GrayHatter** [comment]
@stal888 I assume this is from the update you made a while back. I did have it fixed on windows, but that commit seems to have stopped working.

**Comment by GrayHatter** [comment]
fixed
