### ISSUE TITLE
Feedback from another cross-platform test...

### ISSUE THREAD

**Issue by darkman088** [GrayHatter/uTox#244]
Dear uTox community,

today I have performed a new cross-platform test of uTox, between Windows 7 and Fedora 20.
We have tested the latest version (0.6.1) on both systems.
I will start with, unfortunately, the only positive point: I was hearing my counterpart very well !!
The sound quality has improved a LOT, since the last test I have performed.
Now the bad and buggy points:
1) When my counterpart called me, I immediately click on the button to take the call, but either nothing happens (the ringtone is still ringing, no call is being open), or the call is open, but I still hear the ringtone as well !!
2) Only I was hearing my counterpart (Windows 7), my microphone didn't work, no matter what I tried). In the PulseAudio volume control app, I can of course see the bar moving when I speak, though I wasn't heard on the other side.
3) Video calls were not working at all on neither side. The camera preview button in the options was working flawlessly on my side. The audio preview button was producing very loud noise.

I hope this helps for the further development of uTox and I hope to get some feedback on this report. Thank you very much!

**Comment by cebe** [comment]
> 1) When my counterpart called me, I immediately click on the button to take the call, but either nothing happens (the ringtone is still ringing, no call is being open), or the call is open, but I still hear the ringtone as well !!

same issue as reported here? https://github.com/GrayHatter/uTox/issues/243

**Comment by GrayHatter** [comment]
that should be fixed in develop

**Comment by darkman088** [comment]
Yes, I fully agree with you about 1)
And what about 2) and 3) ? Or your comment, GrayHatter is about all of my points ?

Thanks!

**Comment by GrayHatter** [comment]
this should be fixed, if it still exists in v0.7.1 click the reopen button
