### ISSUE TITLE
No longer able to set avatar image

### ISSUE THREAD

**Issue by flussence** [GrayHatter/uTox#245]
`v0.6.1-24-g50c31993`: clicking the user icon doesn't open a file picker, and dragging an image onto it creates console output but does nothing.

This is a regression, I've got a profile from mid-2015 where I managed to change it from within uTox.

**Comment by GrayHatter** [comment]
Windows? Linux? OSX? Android? Does clicking on the avatar do anything? Can you send a file? Can you save an incoming file?

**Comment by flussence** [comment]
* Linux (Gentoo), compiled with default settings (everything enabled)
* Clicking the avatar does nothing at all, no console output
* Clicking the send file button also does nothing

Going to install qtox to see if receiving works...

**Comment by GrayHatter** [comment]
you need GTK3 installed to access the file manager...

**Comment by flussence** [comment]
Oh, that'd be it... I only have GTK2 here.
