### ISSUE TITLE
UTox for Windows: Screen reader accessibility

### ISSUE THREAD

**Issue by Oire** [GrayHatter/uTox#246]
As a blind user, I would love UTox to be accessible for screen readers.  
It seems, your Windows client uses native Windows API so it should not be difficult to implement this. For instance, now Tab key does not move through objects (or, at least, screen readers don't know about it).

**Comment by cebe** [comment]
@Oire can you give some input on where we find information about how to use native Windows API to make utox pass information to the screen reader?

I have listed some information about this topic in issue https://github.com/GrayHatter/uTox/issues/239 but the links there are for linux, gtk and gnome only.

**Comment by cebe** [comment]
I just tried Tab key, it really does nothing. The UI in general is not very keyboard friendly so a lot of work would be needed to make it useable as far as I see.

**Comment by GrayHatter** [comment]
Making the core keyboard friendly to things other than hotkeys is a LOT of work. There's no realy hierarchy other than parent child. you might be able to define a tab_next, but buttons never have focus, and neither does anything else, so everything would have to be re-written.

Passing events and messages to the screen reader shouldn't be too hard, but again, like @cebe I've never even looked at the api

**Comment by Oire** [comment]
so guys, should I close this in favor of #239 or leave it as is? I'll provide some resources about accessibility in windows. Thanks!

**Comment by cebe** [comment]
yeah, close it and continue in  #239.
