### ISSUE TITLE
Unable to initiate Group Chats

### ISSUE THREAD

**Issue by TokumeiNanashi** [GrayHatter/uTox#255]
Running uTox 0.7.0 in Win 7, I am unable to create a Group Chat as I was before.
In previous versions, right-clicking in the Contacts area to the left of the screen brought up a menu to create a group chat. Since upgrading to 0.7.0, right clicking in that area brings up no menu. As a result, I am unable to create a group chat, and was forced to rely on a Contact running an older version of the software to create one and invite me into it.

**Comment by cebe** [comment]
same on latest `develop` on Debian Linux.
