### ISSUE TITLE
Tiny interface in android

### ISSUE THREAD

**Issue by ebinXD** [GrayHatter/uTox#256]
![screenshot_20160327-225849](https://cloud.githubusercontent.com/assets/18104447/14067630/2bb9de30-f471-11e5-9a06-a49d86553316.png)

I'm using a custom rom (in case it matters) cm13

**Comment by tsudoko** [comment]
Can you change DPI from the settings?

**Comment by ebinXD** [comment]
google tells me I can change it manually by modifying files but I don't feel like globally changing DPI for a single app

**Comment by tsudoko** [comment]
I meant the uTox settings, there should be a dropdown in the UI tab.

**Comment by ebinXD** [comment]
thanks, it works fine now but I can't figure out how to lock threads
