### ISSUE TITLE
uTox GUI freeze

### ISSUE THREAD

**Issue by ghost** [GrayHatter/uTox#259]
I downloaded "utox_windows_x86-64.zip". Extracted 1 exe file from it, and placed it on X:/Something/.
Run utox.exe.

In the Network tab,
1. Turn IPv6 to No,
2. Turn UDP to No

OR

1. Network -> Proxy "Disabled" --> change it to "always use" thing
2. Set IPv6 to No

Both triggers GUI freeze.
Task manager said "uTox" is not responding.

Any ideas?

0.7.0 (tested on Win7 64bit/32bit, same result)

**Comment by espress0** [comment]
https://tox.chat/download.html

**Comment by cebe** [comment]
reproduced on Debian linux, latest develop.

**Comment by nsagentwatchu** [comment]
Any update on this? Same result here...

**Comment by GrayHatter** [comment]
been busy, haven't' forgotten...

**Comment by verycrypt** [comment]
@GreyHatter Unfortunately, this still happens on v0.8, preventing me from using uTox on Windows.
https://build.tox.chat/job/uTox_build_windows_x86_release/lastSuccessfulBuild/artifact/utox_windows_x86.zip

**Comment by verycrypt** [comment]
until then, I'll try qTox... https://github.com/tux3/qTox
