### ISSUE TITLE
Typing notification is covered by input field area.

### ISSUE THREAD

**Issue by juniorV** [GrayHatter/uTox#26]
The notification about user typing in chat appears under message input area.
![utox](https://cloud.githubusercontent.com/assets/12958189/10950431/49a8a9e6-8340-11e5-9c69-22949a06a8b6.jpg)

Thank you!

**Comment by GrayHatter** [comment]
Very interesting, I'll look into it!

**Comment by Doom032** [comment]
Can reproduce on Linux and Wine. Also, typing notification is only visible with the "Dark" and "Zenburn" themes, not in "Default" or "Light". The latter is probably an issue with the colour of the "typing" notification and the background.

If it seems like a waste to have some special room just for the "typing..." notification, maybe we can replace the friend's status with "Typing..." while (s)he's typing. You could also do that in the friend list to the side, so you can see who's typing in every chat. Maybe to make it clear that "Typing..." is not literally your friend's status, it could be shown in an italic font or such.

**Comment by tsudoko** [comment]
I don't think hiding the friend's status while they're typing is a good idea, but I'm not sure where to put the notification instead. I liked the way it was displayed in the beginning, i.e. in the chat area after the last message.

**Comment by GrayHatter** [comment]
@tsudoko it's fixed back to the way it was in ui-rev3

**Comment by GrayHatter** [comment]
fixed
