### ISSUE TITLE
Which link is correct?

### ISSUE THREAD

**Issue by xcatbayx** [GrayHatter/uTox#268]
https://github.com/GrayHatter/utox

On this page,

> top line
> µTox the lightest and fluffiest Tox client http://utox.org

BUT,

> μTox
> The lightweight Tox client.
> Tox Project Website (tox.chat)

...utox.org OR tox.chat? Which is real!?

**Comment by GrayHatter** [comment]
uTox.org is the domain that provides register.utox.org. 

tox.chat provides support to the tox community as a whole... meaning all clients are free to use it.
