### ISSUE TITLE
[Security] Is my IP address leak even if I use Tor?

### ISSUE THREAD

**Issue by xcatbayx** [GrayHatter/uTox#271]
> Does Tox leak my IP address?
> 
> A workaround does exist in the form of tunneling your Tox connections through Tor.
> However, a user cannot uncover another user's IP address using only a Tox ID to find the user in the DHT,
> the IP address will only be discernible when the users become “friends.”

I'm not sure I understand "the IP address will only be discernible when the users become “friends.”".
Does this mean my IP address will leak if I add uTox friends EVEN WHEN I always use Tor?

Also,
If I use Tor with uTox, how uTox send itself to DHT Network?
I mean, does uTox send "my raw IP address(not-tor)" or "local network IP address(192.168.x.x)"?

If Tox core leak my IP address in these situations, this is a big leak I think.

**Comment by GrayHatter** [comment]
If you use tcp only mode, and tunnel everything through tor, you IP address should remain as hidden as tor can offer. uTox is alpha software, as is Toxcore. So you should not count on it to protect your privacy on your identity.

The goal of the project is to protect your privacy and communications, not hide your identity. If you're very concerned about protecting your identity you shouldn't use tox at all yet. We currently make no promises.
