### ISSUE TITLE
Cannot set profile picture

### ISSUE THREAD

**Issue by decomposite** [GrayHatter/uTox#273]
I finally got a picture small enough to be accepted, but when I try to set it utox accepts it but then nothing changes.
profile picture button -> select picture -> click "open" -> absolutely no change

**Comment by GrayHatter** [comment]
Hey, I need some more info on this one.

Can you tell me the OS/Distro? What uTox version you're using? Where you got it? And if you can post the logging output?

**Comment by decomposite** [comment]
I'm sorry! Completely left important information out.

Mac OSX
0.7.0
Brew Cask
I was unable to find any logging output for it. Is there a good place where I can get something verbose?

**Comment by GrayHatter** [comment]
@stal888

**Comment by decomposite** [comment]
Let me know if there's anything I can do to give you more output.

**Comment by GrayHatter** [comment]
@stal888 may have fixed it. can you build the current branch?

**Comment by stal888** [comment]
Since 0.7.1 won't be released anytime soon, you should build from source instead of using casked uTox to test the fix.

See https://github.com/Tox/homebrew-tox for instructions.

**Comment by GrayHatter** [comment]
I assume it's fixed in v0.8

**Comment by decomposite** [comment]
It is! Thanks.
