### ISSUE TITLE
Release version 0.7.0 for linux not available: The specified key does not exist.

### ISSUE THREAD

**Issue by typomedia** [GrayHatter/uTox#277]
I  can not try 0.7.0, because sth. is wrong with the latest releases for linux.
utox_linux_x32-0.7.0
utox_linux_x64-0.7.0

`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
releases/41067120/bf5ed204-eed0-11e5-80e0-47f59e530567.0
</Key>
<RequestId>C38D000F4785885D</RequestId>
<HostId>
dqKatXcV0D9E1rLnNKgBs+eb5H1vQ+KEl/GKmOEX6TdADF7AkRJi1/J4fjOyvihmIARnng17RMw=
</HostId>
</Error>`

**Comment by GrayHatter** [comment]
what's generating that error message?

**Comment by typomedia** [comment]
I am not able to download the latest release builds for linux. Try this:
https://github.com/GrayHatter/uTox/releases/download/v0.7.0/utox_linux_x64-0.7.0

Before they were tar.gz archives.

**Comment by GrayHatter** [comment]
interesting, ill reupload them in a bit :/ sorry about that

**Comment by GrayHatter** [comment]
https://github.com/GrayHatter/uTox/releases/tag/v0.7.0
