### ISSUE TITLE
Broken custom theme support.

### ISSUE THREAD

**Issue by 2a03** [GrayHatter/uTox#28]
Due to discrepancy, introduced in d79822af20e7d69679b3e45013ca687ab2ecff03/_theme_tables.h_, color values parsed from _utox_theme.ini_ are incorrectly mapped to theme colors.

![theme_tables h](https://cloud.githubusercontent.com/assets/5808641/10955727/15b1f53a-8367-11e5-8787-d08c95d78dea.png)

**Comment by stal888** [comment]
Do you want to fix this, or shall I?

**Comment by GrayHatter** [comment]
first one to open a PR wins!

I also added another color type as well
