### ISSUE TITLE
Windows 10 system setting profile password crash

### ISSUE THREAD

**Issue by codejam1024** [GrayHatter/uTox#280]
Can not save the profile password.
Version:uTox-win-x32-0.7.0

**Comment by GrayHatter** [comment]
you should upgrade to v0.7.1

**Comment by GrayHatter** [comment]
https://build.tox.chat/job/uTox-nightly_build_windows_x86-64_debug/lastSuccessfulBuild/artifact/utox_nightly.zip

or 

https://build.tox.chat/job/uTox-nightly-FOR-WIN-XP_build_windows_x86_debug/lastSuccessfulBuild/artifact/utox_nightly.zip
