### ISSUE TITLE
Preferences on Mac does nothing

### ISSUE THREAD

**Issue by PwnArt1st** [GrayHatter/uTox#287]
Clicking uTox then Preferences in the menu bar does nothing.

**Comment by GrayHatter** [comment]
@stal888

**Comment by stal888** [comment]
Can't reproduce this, what build are you running?

**Comment by PwnArt1st** [comment]
using 0.3.2 on osx el capitan

**Comment by GrayHatter** [comment]
consider upgrading https://github.com/GrayHatter/uTox/releases/tag/v0.7.0

**Comment by PwnArt1st** [comment]
I downloaded from the website only the other day, might want to update that then?

**Comment by PwnArt1st** [comment]
Confirm the update works as expected
