### ISSUE TITLE
Bugs with non-Latin filenames

### ISSUE THREAD

**Issue by redmanmale** [GrayHatter/uTox#291]
1. Incorrect appearance of non-Latin filename during transfer:
![screen](https://puu.sh/ogEpX/bb2e17a710.png)

2. Can't send file with non-Latin symbols in its name. After selection via standard SelectFileDialog file doesn't show up in the uTox's interface.

Win 7, x64; uTox v.0.7.1.

**Comment by GrayHatter** [comment]
uTox doesnt' send the correct strings to Windows file dialogs

**Comment by GrayHatter** [comment]
should be fixed in develop
