### ISSUE TITLE
about double release post

### ISSUE THREAD

**Issue by verycrypt** [GrayHatter/uTox#292]
I just want to say one thing - calm down GrayHatter.
No need to post 2 releases posts(mild shock. I'm subscribing to release RSS).

Just take your time, and only post it after completed them.

You can close this issue after reading. Good luck to you.

**Comment by GrayHatter** [comment]
I didn't release two, I threw out a short update on the 20th for everyone who was waiting for the release. Then updated it with a better description when I wasn't tired. 

Sorry you got two posts, I'll try to code faster next time!
