### ISSUE TITLE
Groupchat window can't be scrolled in any way

### ISSUE THREAD

**Issue by tsudoko** [GrayHatter/uTox#298]
When the text overflows, you can't scroll down to see the rest of it, there's no scrollbar either.
adb1e18

update: the scrollbar appears after ~~resizing the window~~ switching to a 1-1 chat and back

**Comment by tsudoko** [comment]
Still happens in dae46ed

**Comment by GrayHatter** [comment]
refixed in 16811e01b24143f80495eb7e4bbc97f60fe4d80a

**Comment by tsudoko** [comment]
Still happens in 232cf169

**Comment by GrayHatter** [comment]
RE FIXED!

hopefully it'll stay that way

thanks and sorry about that @tsudoko
