### ISSUE TITLE
Save Auto Accept settings for uTox

### ISSUE THREAD

**Issue by Serverkill** [GrayHatter/uTox#30]
Hi!

I see that there is one feature missing in uTox that I think is important to a lot of people - autoaccept files!

Like when some friend sends me a files then uTox would automatically accept them and store them in location that I have predefined (desktop).

Of course it should be optional. Disabled by default but when someone wants it, there is option in settings where you can enable it and choose default save location.

I use it a lot on Skype, to transfer some files from one computer to another. 
Or when I'm away from computer then someone can send me something and I can see it when I return. Not all of us have 100mbit connections...

Greetings
SKill

**Comment by tsudoko** [comment]
Agreed, I was trying to implement that a few months ago but I wasn't sure how to do it UI-wise

**Comment by GrayHatter** [comment]
@tsudoko add a dropdown to one of the tabs. If you have a branch, open a PR and I'll take a look.

**Comment by fcore117** [comment]
This feature i miss really much, saves tons of time and speeds up productivity when transferring files and is saving nerves when i sometimes miss clicking on right location.

**Comment by Doom032** [comment]
qTox has both a global autoaccept option and a per friend option. I think that's a good idea.

**Comment by GrayHatter** [comment]
this is done in develop

still needs to save across sessions, but that's easy

**Comment by fcore117** [comment]
now that is a really time saver feature and good usability boost too.

**Comment by Serverkill** [comment]
Thats great, wow!

So I understand that at the moment this setting resets itself when session ends, but you are working on it, so it will stay permanent?

**Comment by GrayHatter** [comment]
I think I fixed that too... right click on a friend, set autto accept to yes, then restart, and revisit, it should be yes.

If not ping me, and I'll find and push the branch

**Comment by fcore117** [comment]
Could you create jenkins branch that builds automatically with every change to toxcore or utox? last utox see is built 9 days ago. I know those can be more unstable but i have utox profile backup always just in case. Serverkill: Do you know how to compile then share some top notch binaries here?

**Comment by GrayHatter** [comment]
@fcore117 you mean this one? https://build.tox.chat/job/utox-nightly_build_linux_x86-64_debug/

**Comment by fcore117** [comment]
https://build.tox.chat/view/Clients/job/uTox_build_windows_x86-64_release/
https://build.tox.chat/view/Clients/job/uTox_build_linux_x86-64_release/
 i meant these, march 7 is last builds.

**Comment by GrayHatter** [comment]
right, those are stable. They only update from the master branch. 

I don't push everything to the master branch, only new versions.

**Comment by fcore117** [comment]
I would like to raport my case that auto accept still wont be remembered and files go my documents when autoaccept was in effect, ofcourse i am portable uTox user on Win and Ubuntu so perhaps this is causing bug or conflict?.

**Comment by GrayHatter** [comment]
can you give me debug output?

**Comment by fcore117** [comment]
how to generate debug on windows, i have this large debug build from jenkins

**Comment by GrayHatter** [comment]
just open it from a terminal and start utox. it will print to the console. that all I need

**Comment by fcore117** [comment]
command prompt stays silent:
![capture](https://cloud.githubusercontent.com/assets/1313813/13904219/d27492fe-eea1-11e5-8cbe-e6c497f966bd.JPG)

**Comment by tsudoko** [comment]
Don't windows applications need to be compiled as console applications to be have access to stdin/stderr?

**Comment by GrayHatter** [comment]
cmd.exe might fork by default... either way, can you run it with cygwin?

**Comment by fcore117** [comment]
dont know if it is right debug file? 
[utox.txt](https://github.com/GrayHatter/uTox/files/185714/utox.txt)

**Comment by GrayHatter** [comment]
No, I need the debug info from uTox. The information that uTox prints.

**Comment by fcore117** [comment]
how is progress with permanent per friend accept remembering?

**Comment by GrayHatter** [comment]
@fcore117  should be fixed NOW in develop

ping me or reopen if it's not

**Comment by fcore117** [comment]
How participants can reopen post? i dont see option here. Still loses options after some close and reopening of utox.

**Comment by fcore117** [comment]
Looks like accept remembering works ok now.

Serverkill if you see this then you can test this too someday when updates will come.

**Comment by Serverkill** [comment]
Hi guys!

I tried yesterday nightly version build (#488).
There are problems, when I enabled autoaccept on friend and he sent me files, filetransfer failed quickly. But when I disabled autoaccept, files came as they should, after I accepted them of course.

Hope this helps somehow!

**Comment by GrayHatter** [comment]
uTox was unable to write to the working directiory
