### ISSUE TITLE
uTox crashes when attempting to send a file

### ISSUE THREAD

**Issue by roranicus** [GrayHatter/uTox#302]
OS: Linux Mint 17.3 Xfce 
version: 0.8.0

I attempted to send files to one of my friends, who's using qTox on Windows, and uTox crashed. I tried twice, and the behavior occured both times. uTox then kept crashing on launch until I went in the Tox folder in .config and deleted all the files with long strings of numbers it creates (I assume they're encrypted log files?)

**Comment by GrayHatter** [comment]
This is already fixed in develop.


I'm going to try to get v0.8.1 out tomorrow night, until then https://build.tox.chat/job/utox-nightly_build_linux_x86-64_debug/ should work for you

**Comment by roranicus** [comment]
I can confirm that it works. Thanks!
