### ISSUE TITLE
0.8.0 Initiating file transfer crashes utox

### ISSUE THREAD

**Issue by ElLamparto** [GrayHatter/uTox#303]
What's worse, after the initial crash, every utox start results in an attempt to resume the file transfer and crash.

Friend-4 State:	1
Friend-4 Typing:	0
FileTransfer:	Attempting to restart existing transfer to friend2.
FileTransfer:	.ftinfo for file AmaUFryzjera.zip set; ready to resume!
Segmentation fault

utox 0.8.0
Debian Jessie 32bit.

**Comment by LittleVulpix** [comment]
@ElLamparto  #302  ?

**Comment by ElLamparto** [comment]
@LittleVulpix, yes it is the same problem. Could you tell me which file holds the transfer information?

**Comment by GrayHatter** [comment]
*.ftout
