### ISSUE TITLE
Version 0.8.1 doesn't always give flash alert or message bubble to alert new message

### ISSUE THREAD

**Issue by DexterMcKinnery** [GrayHatter/uTox#307]
Since uTox updated for me last night, I no longer get notified when my friend sends me a message.

- File transfers still give the alerts and flash at the bottom
- It doesn't matter whether I have the status set to available, away or busy

- I am using Windows 7
- Windows 2000 theme

If you need any more information, please ask and I will try and give! Sorry if this has already been brought up, I couldn't see it!

**Comment by DexterMcKinnery** [comment]
Also, being able to send through and SEE my own messages is very temperamental and sometimes I can't see a conversation happening at all. From me OR my friend. This happens on the windows build AND the linux build.

For example;

- I write a message then send it through. I can't see my own message but my friend can. Restarting uTox on my end usually fixes this, but not always.

OR

- I write a message then send it through. I can see my message, but my friend can't. Restarting uTox on their end usually fixes this, but not always.

OR

- I write a message and send it through. I can't see it. My friend is writing messages and sending them through. I can't see theirs either. No idea what they can or can't see because I can't see anything to find out. Restarting uTox doesn't fix anything.

Weirdly it can change by contact... for example I can be having a problem seeing my messages to contact A, but I can go into the tab with contact B and send and see my messages fine.

This is all in one to one chat, not group.

The chat log from my friend using Antox no longer saves either. Though chat log will save from other friends using uTox. I'm not sure why this would be...

**Comment by DexterMcKinnery** [comment]
Found out that this particular problem;

"I write a message and send it through. I can't see it. My friend is writing messages and sending them through. I can't see theirs either. No idea what they can or can't see because I can't see anything to find out. Restarting uTox doesn't fix anything."

Was to do with chat log... I had a very large chat log with this friend which was obviously causing issues with the new update... I had to delete all chat log files associated with this friend. Not a solution really, but something to go on perhaps.

**Comment by NatkaniecZM** [comment]
I'm having the same issue with the lack of message alerts. There is no sound and no pop-up.
I was also unable to receive or send any messages during the first session after the update, but it seems to have fixed itself after a restart. 
I'm running Win7 as well.

**Comment by DexterMcKinnery** [comment]
Agreed on the messages on the first session to each contact after the update.

Also, no circle around the contact's online graphic after receiving a message so I have to keep checking all the chats to see if they've said anything. This happens on Linux too!

**Comment by jcherqui** [comment]
:+1:
