### ISSUE TITLE
/tools/logs_to_plaintext.c needs to be updated

### ISSUE THREAD

**Issue by GrayHatter** [GrayHatter/uTox#309]
Consider rolling it into uTox itself

**Comment by utoxxer** [comment]
Thanks. I like the idea of utox rolling this in and supporting plaintext logs, but at the same time I prefer the date/time format to be closer to ISO 8601 format similar to toxic logs so that it's easier to parse in the future. Having it separate lets me make that change before compiling logs_to_plaintext.c. Maybe timestamp format could be an option if you do decide to integrate it.

**Comment by tsudoko** [comment]
Text logs are a good idea, but I'm not sure if they wouldn't be too much of a pain to parse.

**Comment by utoxxer** [comment]
Here's a version of logs_to_plaintext.c that should create logs that are easy to parse (can search "2016-05-04" instead of "May <time><timezone> 2016"
https://ideone.com/gBoNFc

**Comment by tsudoko** [comment]
There would be a need to escape logs pasted in conversations to avoid confusion when parsing, that's where things get messy.

**Comment by c251** [comment]
utox used to at least have an annoying workaround to be able to save chat logs and view them later (logs_to_plaintext). now for the past month or more this is broken stopped using it. and i see the milestone just got pushed back. i love utox but come on, a chat client really needs a way for its users to easily pull up logs (see toxic for example). guess i'm stuck using pidgin for the time being.

**Comment by utoxxer** [comment]
c251, I'm in the same boat. However I haven't resorted to pidgin. Toxic supports logs like you said. I am using utox 0.7 since logs_to_plaintext.c still works with it. The bugs in that version are worth it to be able to view chat history.

**Comment by GrayHatter** [comment]
you can export a chat history in the multi-device branch

Porting JUST that feature back to develop is more work then I'm willing to spend

**Comment by fsignal** [comment]
Awesome. Looking forward to this export feature showing up in the stable binaries sooner or later.
