### ISSUE TITLE
Recent utox versions re-send entire message history every time a friend comes online

### ISSUE THREAD

**Issue by flussence** [GrayHatter/uTox#312]
Seems to be since the messages-queue branch was merged. I've made sure the people on the other end are all up to date with their clients.

**Comment by GrayHatter** [comment]
@flussence I believe I've fixed this issue. Can you tell me what version/git-revision you're using?

**Comment by flussence** [comment]
Was using a5f70ac4 (I think), and one version between that and the branch merge I don't remember. 035f2c1e seems to have no problems.
