### ISSUE TITLE
utox kills itself trying to malloc insane amount of memory at startup

### ISSUE THREAD

**Issue by flussence** [GrayHatter/uTox#313]
Just got this while trying to reproduce the issue I filed before this one:

```
$ utox
Can't malloc that much, you'll probably have to move or delete, your history for
this peer.
                Friend number 0, count 1, actual_count 6, start at 0, error size
                67108864
```

My `~/.config/tox/` is 4.5MB total, and I have about 900MB free RAM, something doesn't add up.

**Comment by GrayHatter** [comment]
you'll have to delete that log, and restore from backup
the newest version in `develop` SHOULD have this fixed

**Comment by flussence** [comment]
Looks like the log causing the crash may have had garbage in it from the last time toxcore changed the message format incompatibly, if that's useful to know.

**Comment by GrayHatter** [comment]
yeah, it should be fixed in `develop` as well

**Comment by fcore117** [comment]
lastest working develop from jenkins still closes with similar output.

Can't malloc that much, you'll probably have to move or delete, your history for this peer.
		Friend number 0, count 1, actual_count 1, start at 0, error size 1463000055

**Comment by GrayHatter** [comment]
@fcore117 what's the git version listed on the settings page?

**Comment by fcore117** [comment]
https://build.tox.chat/job/uTox-nightly_build_windows_x86-64_debug/ lastest that comes from here

**Comment by GrayHatter** [comment]
@fcore117 do you have backups that you can restore?

The logs you have now are obviously corrupted, but I need to know if v0.8.2 is still corrupting them? Or if that problem is from before?

**Comment by GrayHatter** [comment]
make sure if you're restoring from backups that you still keep a copy so that you can try again if I do need to fix something.

**Comment by fcore117** [comment]
i do not use logging currently, i only have multiple backups of tox_save.tox

**Comment by GrayHatter** [comment]
I don't understand, if you don't have any logs then there should be no way to get this error.

**Comment by fcore117** [comment]
weird thing is i discovered that logging is disabled but still logging is running

**Comment by GrayHatter** [comment]
I found the issue on windows... it's fixed now

let me know if you have this issue anywhere and I'll reopen this!
