### ISSUE TITLE
Super small window on start

### ISSUE THREAD

**Issue by redmanmale** [GrayHatter/uTox#314]
On start uTox always looks like that:

![screen](https://puu.sh/oN5iM/083fd5d6dc.png)

Win 8.1 x64, v.0.8.1

**Comment by GrayHatter** [comment]
does `%AppData%\Roaming\Tox\utox_save` exist?

**Comment by redmanmale** [comment]
Yes. I removed it and bug is gone.

**Comment by GrayHatter** [comment]
we need min ranges for these settings.

**Comment by cebe** [comment]
isn't there already a min range defined? I can not make the windows smaller than some threshold by hand so that should be applied here.
