### ISSUE TITLE
blue text and dark theme

### ISSUE THREAD

**Issue by fcore117** [GrayHatter/uTox#315]
Please change just written text color in dark theme to something mild like amber-yellow or something other mild tone

**Comment by cebe** [comment]
you mean this text, right?
![bildschirmfoto von 2016-05-10 21 48 11](https://cloud.githubusercontent.com/assets/189796/15160223/f56f8730-16f8-11e6-8e53-c03109781753.png)

**Comment by cebe** [comment]
alternatives:

## 0xaaccff

![bildschirmfoto von 2016-05-10 22 05 11](https://cloud.githubusercontent.com/assets/189796/15160708/4de28262-16fb-11e6-91ac-284af90d0c90.png)

contrast ratio:
https://leaverou.github.io/contrast-ratio/#%23aaccff-on-%23333333

## 0x66ccff

to differentiate more from normal text.


![bildschirmfoto von 2016-05-10 22 07 45](https://cloud.githubusercontent.com/assets/189796/15160781/a8f96030-16fb-11e6-8ee0-4b2b9a585a0e.png)

contrast ratio:
https://leaverou.github.io/contrast-ratio/#%2366ccff-on-%23333333

**Comment by GrayHatter** [comment]
* bookmarks that site!

**Comment by fcore117** [comment]
cebe: yes i meant that blue

**Comment by fcore117** [comment]
merged already, did not see. Thanks.
