### ISSUE TITLE
Offline messages are delivered in wrong order

### ISSUE THREAD

**Issue by cebe** [GrayHatter/uTox#316]
![bildschirmfoto von 2016-05-10 21 56 28](https://cloud.githubusercontent.com/assets/189796/15160512/3e537e56-16fa-11e6-932d-f95eef15857a.png)

**Comment by cebe** [comment]
not sure if it is random or always reverse order...

**Comment by GrayHatter** [comment]
it's reverse order because I didn't want to loop through the list twice, nor did I want to search the list from the start everytime a friend connects. It's still missing some logic, so currently, there's no good reason for this.

**Comment by GrayHatter** [comment]
fixed in develop
