### ISSUE TITLE
The baloon is gone

### ISSUE THREAD

**Issue by darkman088** [GrayHatter/uTox#319]
Dear uTox developers,

in former versions, there was a very nice featre - when somebody writes me something,
a baloon with the text was appearing, so it wasn't necessary to switch every time to Tox.
Now in the latest version we don't witness this feature anymore...
Can you please kindly briefly explain why and me and my contacts would be very very
happy, if this feature could be reintroduced again!
Many thanks in advance !!

**Comment by GrayHatter** [comment]
@darkman088 do you mean a tray notification in windows?

**Comment by darkman088** [comment]
yes Sir!

**Comment by GrayHatter** [comment]
Shouldn't be, I'll take a look

**Comment by GrayHatter** [comment]
Works for me in W10 develop branch, if it's still broken, and you verify you haven't blocked uTox from creating notifications please provide more information on what behavior you expect, what you see, and what I need to do to duplicate the problem

**Comment by darkman088** [comment]
Thank you, GrayHatter - I just updated to version 0.9.4 under Linux. I don't see the baloons. I am not aware of any way to block such functionality in Windows.
I will have to also test this in Windows 7, I apologize for not doing it yet. Many thanks!
