### ISSUE TITLE
uTox not responding after it connects

### ISSUE THREAD

**Issue by erejnion** [GrayHatter/uTox#334]
After updating to 0.9.1, entering my password, uTox shows the changelog, allows me to enter the settings and even change them, loads the saved logs for the people in my contact list, but then crashes when it makes the first connection to another user in my contact list. More specifically, it crashes the moment it makes the sound notification. Waiting it out doesn't fix it. 

System: Win7 64 bit, all updates installed, on a Lenovo E560, again with all drivers shipped by Lenovo for the moment.

**Comment by GrayHatter** [comment]
Does it crash and close? Or does the UI just hang?

**Comment by drgfire** [comment]
i have the same issue, using win10 64-bit.

it doesn't crash and close. the ui hangs, and clicking on it just gets windows to say the program is unresponsive. there doesn't seem to a way to avoid it.

**Comment by GrayHatter** [comment]
do you have cygwin installed on your computer by chance?

**Comment by GrayHatter** [comment]
if you set your status to busy before the friend comes online does that fix it?

**Comment by drgfire** [comment]
i don't have cygwin installed on my computer.

setting my status to busy before my friends come online doesn't fix it. i also tried setting myself to away, but it made no difference.

**Comment by GrayHatter** [comment]
@drgfire is it any friend? or just the one friend?

**Comment by GrayHatter** [comment]
a temporary solution may be (backing up) and then removing or deleting the history for any friend that hang's uTox

You can right click on the friend to delete history, but that WILL **NOT** backup. If you need to backup your history I can provide information on it.

If you have history for a friend that you know makes uTox crash, and you can send me the history file it'll make it easier to track down this issue

**Comment by drgfire** [comment]
it looks like it's all friends that cause it to crash, though i'm not completely sure. i tested it by having the same friend log onto qtox and log out of utox. when their qtox-profile came online, it also caused the program to hang. 

i tried clearing the history (also while set to busy, dunno if that would impact anything) and it didn't cause the program to crash. 

i sent a few messages, then restarted utox. re-opening it didn't hang when the friend came online, even without clearing the new history. it doesn't matter if i'm online or if i'm on busy. 

dunno if this applies to all chats, or just the chats where the history has been cleared.

**Comment by erejnion** [comment]
My issue is the exact same as dgfire's, I confirm everything he said up to clearing the history. It crashes on the first connection, and so far it's managed to connect to only two different users as firsts, so iunno if it would hang on all. I will now try clearing the history. I'll first backup the logs, they are those in AppData/Roaming/Tox, right?

**Comment by GrayHatter** [comment]
@erejnion that is correct

**Comment by GrayHatter** [comment]
This should be fixed in v0.9.3

Please let me know either way.

**Comment by erejnion** [comment]
Everything works perfectly now, thanks!
