### ISSUE TITLE
uTox (v0.8.2 - 0.9.1) automatically exit under Win10

### ISSUE THREAD

**Issue by uname2p** [GrayHatter/uTox#341]
System：Windows 10
Version：0.8.2 - 0.9.1
Yesterday 0.8.2 is also the perfect run, but it is not today, the latest version (0.9.1) also exists the problem of automatically exit
v 0.7.1 - 0.8.1 can run perfectly under Win10

All versions can run perfectly under Win7

Under Windows 10:
![animation3](https://cloud.githubusercontent.com/assets/19523804/15502767/8ddddcca-21e8-11e6-8993-f574b475daac.gif)

**Comment by zestyr** [comment]
I believe this is because of the "Can't malloc that much" error, which you only get when running from a terminal. The 'solution' seems to be renaming your tox folder (that holds your user profile and chatlogs), which obviously shouldn't be necessary.

Here's some terminal output showing the above.

```

~ ❯ utox
Can't malloc that much, you'll probably have to move or delete, your history for this peer.
		Friend number 0, count 4, actual_count 1, start at 0, error size 432345564227567616%             ~ ❯ cd .config/
.config ❯ mv tox tox_backup
.config ❯ utox
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed

(utox:3643): Gdk-WARNING **: utox: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

.config ❯ mv tox_backup tox
.config ❯ utox
Can't malloc that much, you'll probably have to move or delete, your history for this peer.
		Friend number 0, count 4, actual_count 1, start at 0, error size 432345564227567616
```

**Comment by GrayHatter** [comment]
upgrade to v0.9.3

https://build.tox.chat/view/uTox/

**Comment by zestyr** [comment]
I got that error after updating to v0.9.3

**Comment by GrayHatter** [comment]
@zestyr your chat history is somehow corrupted, you'll have to delete that log file.

If there's information in it you need to keep I can try to help you recover it, but there's not really any other alternative.

**Comment by uname2p** [comment]
Delete all files of chat, uTox perfect running.
All versions can run perfectly under Win10.
Thank you very much

**Comment by benzmiller** [comment]
I'm also having this issue with 0.9.4. I have uTox set to open in the tray, and when I run uTox runner, it has the icon in the tray, then the second I put my mouse over it, it disappears. Is the log file that you're saying to delete the one in the uTox folder? I tried that and it didn't do anything different.
Running on Windows 7.

**Comment by GrayHatter** [comment]
@benzmiller it'll be in %AppData%\Roaming\Tox\  it's the HEX_ID_OF_FRIEND.new.txt

**Comment by benzmiller** [comment]
@GrayHatter Working fine again. Thanks!

**Comment by redmanmale** [comment]
Confirm. Removing all chat files fixes problem.
But it's a little sad to lose history just because of tox client update.

**Comment by GrayHatter** [comment]
@redmanmale one of the entries is corrupted.

If you still have the history file, find me on IRC and I'll walk you through the repair steps
