### ISSUE TITLE
Language settings: Always resets to default (local language) after restart

### ISSUE THREAD

**Issue by jhdohrmann** [GrayHatter/uTox#342]
In uTox Settings > Profile, I want to change the UI language. I can do so temporarily -- for the duration of the current uTox session. However, I don't know how to store the setting, persistently. After I close and restart, the language is always reset to the original default. (In my case, it seems to reset to my local language, other than english.) 

Please tell me, if I use the programm wrong. Should there be a "Save" or "OK" button, which I simply don't see?

Noticed at several uTox versions (0.8.* until 0.9.3, by now)

**Comment by GrayHatter** [comment]
OS?

**Comment by jhdohrmann** [comment]
Windows 8.1 (x86-64)


-------- Ursprüngliche Nachricht --------
Von: Gregory Mullen <notifications@github.com>
Gesendet: 25. Mai 2016 03:39:35 MESZ
An: GrayHatter/uTox <uTox@noreply.github.com>
CC: Jan-Hendrik Dohrmann <jan-hendrik.dohrmann@web.de>, Author <author@noreply.github.com>
Betreff: Re: [GrayHatter/uTox] Language settings: Always resets to default (local language) after restart (#342)

OS?

---

**Comment by tsudoko** [comment]
By default uTox uses your system language, the choice isn't saved anywhere.

**Comment by jhdohrmann** [comment]
Thanks for this info. Can I request the possibility to store the
language choice, then? Would mean significant convenience.

(Almost everytime I use uTox for a while, I manually change language,
because my local language looks ugly in UI (overlapping labels -- but
that may be topic of a different ticket...), and the english
descriptions are also more coherent to me.)

Best regards!


Am 25.05.2016 um 12:14 schrieb tsudoko:
> By default uTox uses your system language, the choice isn't saved anywhere.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GrayHatter/uTox/issues/342#issuecomment-221531376>
> 

-- 
Jan-Hendrik Dohrmann | Sprockhöveler Str. 129 | 58455 Witten | Germany
phone: +49 163 1537298
mailto:jan-hendrik.dohrmann@web.de

PGP-Key-ID: 0x8B3813A6 | Expiry Date: 2017-04-05
PGP-Key-Fingerprint: B6FA 8C83 31D5 FC2A 156F 9350 EFA6 25C4 8B38 13A6

S/MIME Certificate from StartCom Ltd. | Expiry Date: 2017-03-23
S/MIME Certificate's SHA1-Fingerprint:
AA:BB:ED:C1:2A:E6:F8:6C:82:F3:48:8A:F4:2B:8B:6E:BC:6D:63:13


Hinweis: Für vertrauliche/authentische E-Mails:
E-Mail-Verschlüsselung auf Basis der Standards S/MIME oder OpenPGP.
Anleitungen z.B. hier:
https://emailselfdefense.fsf.org/de/infographic.html
https://www.verbraucher-sicher-online.de/thema/e-mail-verschluesselung

Note: For confidential/authentic Email:
Email-encryption based on standards S/MIME or OpenPGP. A quick guide:
https://emailselfdefense.fsf.org/en/infographic.html

**Comment by redmanmale** [comment]
Already reported this bug: (https://github.com/GrayHatter/uTox/issues/96)

**Comment by tsudoko** [comment]
Right, closing in favor of #96

**Comment by redmanmale** [comment]
But in #96 it doesn't fixed. This bug is still here.

**Comment by jhdohrmann** [comment]
Thank you for the support. I didn't notice this was already reported; thanks for the reference.

**Comment by GrayHatter** [comment]
@redmanmale this issue was closed, because you issue #96 is still open and pending... no reason to have two of them
