### ISSUE TITLE
User Interface Settings: Non-english labels overlap

### ISSUE THREAD

**Issue by jhdohrmann** [GrayHatter/uTox#346]
STR:
0) Open uTox
1) Configure certain non-English UI languages via: uTox Settings > Profile > Language. For instance: Deutsch, Espanol, Italiano, Norsk, Polski, Russian, ...
2) Go to uTox Settings > User Interface (or whatever it's called in the respective language) 
--> Certain labels overlap so that it is really hard to read 

Example Screenshot:
![utox_screenshot__overlapping_labels](https://cloud.githubusercontent.com/assets/6828139/15592772/b5258d04-23a6-11e6-8451-f3ea67c5fb3f.PNG)

Workaround: 
Switch back to a language, that does not show these symptoms

Environment: 
* Windows 8.1 (x86-64),
* uTox: noticed in several versions from 0.8.* to 0.9.4. 
* Maybe of importance: High-DPI-Display; Windows 8.1 scaling set to 200%

Best regards!

**Comment by cebe** [comment]
a simple fix would be to just put the second one on a new line.

**Comment by GrayHatter** [comment]
They were supposed to float... But yeah, my plan has been to move that to a new line once I add toggle buttons over dropdowns

**Comment by Getron** [comment]
Same problem here on Linux Netrunner 2016.01 KDE Arch Rolling release.

**Comment by GrayHatter** [comment]
fixed with switches
