### ISSUE TITLE
Windows XP version error ("RegDeleteKeyValueW" and ADVAPI32.dll)

### ISSUE THREAD

**Issue by justa9** [GrayHatter/uTox#349]
Hello!

The latest Windows XP version reports the following error:
"The procedure entry point RegDeleteKeyValueW could not be located in the dynamic link library ADVAPI32.dll".

This seems to be caused due to the fact that the above entry point is present only in the Windows Vista version of ADVAPI32.dll.

**Comment by GrayHatter** [comment]
@irungentoo can you rebuild the legacy version to confirm that's not the issue?

**Comment by GrayHatter** [comment]
@justa9 where did you get your utox.exe?

**Comment by justa9** [comment]
I used this link:
https://build.tox.chat/job/uTox-nightly-FOR-WIN-XP_build_windows_x86_debug/lastSuccessfulBuild/artifact/utox_nightly.zip

**Comment by GrayHatter** [comment]
@justa9 sorry, that was my mistake... it should be fixed now.

Please let me know if it's not?

**Comment by justa9** [comment]
The new version (same link) works as expected. 

Thank you very much!
