### ISSUE TITLE
profile import/export (uTox portable)

### ISSUE THREAD

**Issue by alugarius** [GrayHatter/uTox#357]
Adding *.tox import export and an portable mode where the files are stored in the same dir as the binary.

**Comment by fun4jimmy** [comment]
There is already a portable mode that does this.

Run "tox.exe --portable".

**Comment by tsudoko** [comment]
Portable mode is already implemented, profile import/export was requested in #206

**Comment by darkman088** [comment]
Hello everybody,

I'm sorry for still digging into this, but I would very kindly like to ask, if it's not possible to add a
"Porable mode: Yes/No" combobox in the Profile tab in Settings for this ?

**Comment by GrayHatter** [comment]
sure, open an issue for it

**Comment by darkman088** [comment]
Many thanks, GrayHatter, I have done so:

uTox - portable mode option #400
