### ISSUE TITLE
How to static binary

### ISSUE THREAD

**Issue by alugarius** [GrayHatter/uTox#358]
I am a bit confused after trying the BUILD.md

Is there an easy compile uTox static binary?

**Comment by tsudoko** [comment]
[Jenkins](https://build.tox.chat/) provides builds with libtoxcore and the media libs statically linked in, but I'm not sure if scripts used in the build process can be looked at.

**Comment by alugarius** [comment]
I just want to know how to do it myself, to be independent from Jenkins.
Or is this kind of build already there?

**Comment by GrayHatter** [comment]
`CFLAGS=-static make` should work
