### ISSUE TITLE
Noise cancellation

### ISSUE THREAD

**Issue by Garve** [GrayHatter/uTox#363]
Hi!

I read that noise cancellation was implemented a long time ago, but it doesn't show up in the settings. Neither in uTox 0.9.4, nor qTox. Using Fedora 23.

![utox](https://cloud.githubusercontent.com/assets/932327/15986383/f88c017e-3006-11e6-827b-cb2d0d6c0cae.png)

**Comment by GrayHatter** [comment]
@Encrypt is fixing this now
