### ISSUE TITLE
properly handle non-multidevice nodes

### ISSUE THREAD

**Issue by davidak** [GrayHatter/uTox#371]
non-multidevice nodes send the messages only to the node where they was added as friend.

it should not be possible to communicate (chat/voice-/video-call) with incompatible nodes.

on each side should be a message that the node with older version needs to update.

**Comment by GrayHatter** [comment]
I have no plans to do this. As soon as multi-device gets merged into irungentoo's repo. Even if your client doesn't support multi-device, toxcore will do everything for you.
