### ISSUE TITLE
Avatar doesn't stick

### ISSUE THREAD

**Issue by stephantual** [GrayHatter/uTox#375]
100px by 100px 32k PNG, avatar is never used nor does it appear when i try to set it. 
utox osx elcapitan latest
v0.4.2-1 g355b81f4

**Comment by GrayHatter** [comment]
@stal888 is this the version you're using?

**Comment by stal888** [comment]
Grab the latest from https://github.com/GrayHatter/uTox/releases and see if the issue is still there. It should have been fixed a while ago but you are using a very old uTox.

**Comment by nochecksum** [comment]
Confirmed not working in v0.4.2
Confirmed working in v0.9.4💃

**Comment by GrayHatter** [comment]
thanks @nochecksum
