### ISSUE TITLE
TRUE is not defined in xlib/main.c and others

### ISSUE THREAD

**Issue by helium-software** [GrayHatter/uTox#38]
Current uTox (commit 1316542e) fails to compile on my system because it's missing a definition of TRUE:
```
In file included from main.c:15:0:
xlib/main.c: In function 'init_ptt':
xlib/main.c:199:35: error: 'TRUE' undeclared (first use in this function)
```
Other files that are probably affected (I didn't check if the included libraries happen to define TRUE/FALSE):
* xlib/dbus.c
* xlib/mmenu.c
* windows/dnd.c
* windows/main.c
* xlib/gtk.c (only in a commented-out statement)

As an alternative to `#define`-ing TRUE and FALSE, the instance in xlib/main.c could also be corrected to title-case `True` since that's available from the X includes.

How did you manage to compile the code in its present state?

**Comment by GrayHatter** [comment]
> How did you manage to compile the code in its present state?

Because I have `TRUE` defined somewhere else? (best guess)...

Take a look at #36 and if that fixes your issue, I'll merge that today.

**Comment by tot-to** [comment]
I have the same problem with compilation from tox-overlay in Gentoo.
https://github.com/zetok/gentoo-overlay-tox/issues/90

**Comment by cebe** [comment]
@helium-software @tot-to could you try with the latest changes from develop branch?

**Comment by GrayHatter** [comment]
closing, because the commit was merged into develop. Tag me and I'll reopen if needed
