### ISSUE TITLE
Corrupting history?

### ISSUE THREAD

**Issue by redmanmale** [GrayHatter/uTox#380]
After restarting laptop uTox began to crash on start (just like in #109 or #341). No Windows updates, same uTox version.
Removing history fixed problem, but it's not good at all.

Win 8.1 x64, v.0.9.4

**Comment by GrayHatter** [comment]
> but it's not good at all. 

That's an understatement

if it happens again let me know if I can see the history, of one corrupted while in use. I can find and fix the problem.

**Comment by redmanmale** [comment]
I found out which history file causing crash.
I could send it to you.

**Comment by GrayHatter** [comment]
this is my toxid DD2A1340FECE441206B5F3D202E6146E76617270214499B72C5511FCE839F85B28D7EACBC46C

**Comment by GrayHatter** [comment]
It seems to be related to name changes being written to disk with the incorrect length. In theory, this shouldn't happen but that doesn't mean much. 

The good news is that it's just the length written to the struct, so if we search for the `\n` char that's appended to make the bin.save more readable, we should be able to fix, or at least ignore broken messages.

**Comment by GrayHatter** [comment]
so, I think I have this fixed in develop, you can open this, or another issue if you ever see the problem again. 

In that case I'll write a more indepth fix
