### ISSUE TITLE
Very network inefficient

### ISSUE THREAD

**Issue by h1z1** [GrayHatter/uTox#387]
Either a bug in the protocol itself or left up to clients to deal with I'm not sure but installed on an S7,  it's _extremely_ chatty.   Bit worse is the client not backing off hosts that are down / unreachable.  There are two hosts for example constantly sending ICMP unreachable yet the client is constantly trying to connect to it.

Given the S7 is a phone, the client shouldn't connect to more then one or two hosts and be extremely forgiving before retries.  Otherwise it kills the battery.   Perhaps a way to specify specific nodes and only those ?

**Comment by GrayHatter** [comment]
That's a part of how the core library was designed. I'm working on fixing it up right now, but it's going to take some time.

In the mean time, I've been told that Antox/Antox written by @wiiaam is much kinder to Android.

**Comment by h1z1** [comment]
Ah, thanks.  If /when you need a test let me know.  Tried Antox it crashed after hitting register and won't restart lol.

**Comment by GrayHatter** [comment]
@wiiaam ^^

**Comment by wiiaam** [comment]
@h1z1 what device were you using? currently there is no support for amd64 android devices due to a library not being available

**Comment by h1z1** [comment]
Interesting.  It's the Samsung Galaxy S7 (G930W8 so arm64).  App appears to run, but unstable(?)   Or it's not really doing what I think it is.  Certainly blew through a lot of data.

**Comment by wiiaam** [comment]
@h1z1 Android 6? Currently permissions are not fully implemented so you will need to grant them manually in Android Settings > Apps > Antox > Permissions

@GrayHatter Does utox support 6 permissions already?

**Comment by GrayHatter** [comment]
nope, but then I don't use many

**Comment by wiiaam** [comment]
Doesn't it need to write to storage for storing the profile?

**Comment by GrayHatter** [comment]
you don't need write permissions to write to /data/data/app/files

**Comment by h1z1** [comment]
Problem with atox is it doesn't start at all after the initial run.  I tried:

- installing atox
- granting storage access
It ran once, crashed when I hit register

- reinstalled, granted full permissions
Same thing, ran once and bails

If there is something I can provide go nuts.  I know UNIX and Linux quite well.  Android, is a bit of an abomination.  I know it runs Linux but it's very different for me.  Translation - I don't see any errors pop up, that isn't to say there aren't any buried in a log file.   I partially got atox to compile yesterday, kinda gave up trying to compile libtoxcore lol.   Crazy dependencies.

**Comment by GrayHatter** [comment]
https://github.com/Antox/Antox/issues

**Comment by h1z1** [comment]
Sorry why was this bug closed?  I get the discussion drifted to atox but the original issue remains wrt network utilization.

**Comment by stal888** [comment]
The high network usage is a long-standing issue with toxcore (i.e. nothing can be done to fix it from uTox). It might be more appropriate to create an issue on the toxcore repo, however, it is unlikely to be fixed in this while...
