### ISSUE TITLE
Very network inefficient

### ISSUE THREAD

**Issue by h1z1** [GrayHatter/uTox#389]
@GrayHatter  Not sure why #387 was closed? 

Still trying to understand Github, it's my understanding I cannot reopen #387 as it was closed by you.  Experience has taught me people by default ignore closed issues, thus recreating.

Thanks

**Comment by GrayHatter** [comment]
You should be able to reopen issues I've closed.

Otherwise I closed it because it became an Antox support thread, and this is the uTox repo.

Also, I believe the same thing about closed issues, but I'm not going to forget that toxcore uses a lot of data. That's why I closed the last one.

**Comment by h1z1** [comment]
Not sure what happened, I didn't see the button :(  Closing this, sorry.
