### ISSUE TITLE
DPI font size bug

### ISSUE THREAD

**Issue by azlux** [GrayHatter/uTox#399]
DPI : BUG. PLEASE REPORT
OS : win8.1 entreprise 64bits (6.3, version 9600)
![capture](https://cloud.githubusercontent.com/assets/11210117/17177457/c8250de4-5411-11e6-80cf-886b99773a8e.JPG)
Last version updated this morning from the default automatic update method.
(the file version say : 640.9.7 )
Az

**Comment by GrayHatter** [comment]
Do you happen to remember what DPI you had set before you restarted?

**Comment by azlux** [comment]
It's was the default : 100%

**Comment by drgfire** [comment]
is this a similar thing to #351 ?

i started having this issue on v.0.9.7 in win10 pro 64-bit. i updated to it from 0.9.4 where there was no problem for me.

are older utox binaries posted anywhere? i can't seem to find them. i want to downgrade to try making it usable again.

**Comment by azlux** [comment]
@drgfire Yes I think this can be the same issue
