### ISSUE TITLE
Initial window paint relies on racy window manager resizing to work properly

### ISSUE THREAD

**Issue by flussence** [GrayHatter/uTox#40]
(repost of notsecure/uTox#1146, thought it was fixed but turns out it was only intermittently working)

Got an image this time, the red border is the compositor's drop shadow:

![2015-11-12-145325_940x699_scrot](https://cloud.githubusercontent.com/assets/409860/11121601/b26584ae-894e-11e5-9540-c49b72bd4844.png)

Steps to reproduce:

1. Put this in openbox's rc.xml (haven't tried with other WMs, sorry):  
    `<application class="utox"><decor>no</decor></application>`
2. Start uTox and resize it to something not default
3. Close and reopen it repeatedly, eventually it'll end up looking like the above.

It doesn't seem to be as simple as replacing mentions of `DEFAULT_{WIDTH,HEIGHT}` with `save->window_{width,height}`... I've tried that and it seems to make the problem worse.

**Comment by GrayHatter** [comment]
@flussence try PR #41

**Comment by GrayHatter** [comment]
if it doesn't work send me an issue of the new problem.

**Comment by flussence** [comment]
Works great. Problem seems to be fixed there.

**Comment by GrayHatter** [comment]
@flussence could you disable your custom openbox settings for utox, try it again, then re-enable them and try it one last time?

**Comment by flussence** [comment]
Okay, done that, tried changing the window sizes a few times too. Everything seems well-behaved.

**Comment by GrayHatter** [comment]
merged
