### ISSUE TITLE
Cross traffic between chat threads

### ISSUE THREAD

**Issue by david-burleigh** [GrayHatter/uTox#401]
My friend in Argentina, who was using uTox version 0.8.1 on a Mac (I'm using qTox), reported to me that some text from a conversation he was having with someone else showed up in a conversation he was having with me, but that text did not appear in my view of that same conversation with him. I'm attaching a screen shot he sent me from his computer, showing the text that cross over somehow. It's the text from the words "Bat Levav" through "Yellow Deli kombi".
![utox-inline](https://cloud.githubusercontent.com/assets/5530825/17216756/e41969b6-54af-11e6-9499-7ead9cd1145c.png)

**Comment by GrayHatter** [comment]
I'm aware of this issue, it was fixed in version 0.8.3 IIRC, you should also upgrade to v0.9.7

Maybe @stal888 will compile a new version.

**Comment by stal888** [comment]
0.9.7 is built and available at https://github.com/GrayHatter/uTox/releases/tag/v0.9.7

**Comment by david-burleigh** [comment]
Wonderful, thank you!
