### ISSUE TITLE
Windows version uTox compile problems.

### ISSUE THREAD

**Issue by Li-albert** [GrayHatter/uTox#405]
I want to cross compiling uTox of windows version in linux circumstance.

QAQ1:The question is the codes in git here cannot use cygwin-compile.sh in tools folder to get the right compling due to the inconsistent logical compiler.

QAQ2: can not visited any more.How can i get toxcore,openal and filter_audio,the three dependent libraries mentioned in the text.

**Comment by GrayHatter** [comment]
If you're using cygwin, you can set $CC to mingw64 and `make` should work.

It's at https://build.tox.chat/ now
