### ISSUE TITLE
Multiple Instances running causes conflict

### ISSUE THREAD

**Issue by xenez** [GrayHatter/uTox#407]
I'm using uTox version 0.9.7 on kubuntu 16.04.1 and when 2 instances of the client are running their is conflict between the 2 related to notifications. If someone is typing a message the clients light up like a christmas tree flipping the person sending the messages online status online and offline. It happens for both users even if only 1 person has 2 instances open

**Comment by GrayHatter** [comment]
You can't run two instances of a single tox profile. That's expected.

**Comment by xenez** [comment]
@GrayHatter Well I managed to... Now granted this did arise after some weirdness I experienced with Plasma 5 seg faulting but I did somehow manage to get 2 instances running. I can try and reproduce and will post another issue if I have more information that pinpoints the issue. Sorry for wasting your time.

**Comment by GrayHatter** [comment]
@xenez I mean to say, you shouldn't. Tox isn't designed to be used from multiple computers/devices. Running the same profile twice on the same computer has the same effect. Once the second connects, the first gets disconnected.
