### ISSUE TITLE
startup regression (reading config)

### ISSUE THREAD

**Issue by felix-salfelder** [GrayHatter/uTox#413]
just upgraded (tried to). f9d78435835714 compiles and runs. when i start utox, it seems that no config is loaded at startup. the "utox Settings" form shows up, but remains blank.

the commit message of that commit says `drop [..] support for ancient save format`. however, this save format must have been used until very recently. i don't think its a good idea to drop it...

is it just me? can i convert the config? all config files i can find are binary.

thanks

**Comment by GrayHatter** [comment]
I don't understand the problem, what's not showing up?

**Comment by felix-salfelder** [comment]
uTox is starting, then shows the "uTox settings" screen, with the "profile" tab selected but all forms empty.

what i did: use the version tagged 0.9.4 for a while, then switched to 0.9.8. i bisected this down to the  commit mentioned above. and it seemed logical, as that commit touches config settings loading.

BUT: whatever the problem was, now i cannot reproduce (wanted to post a screenshot). thats confusing.

thanks for asking, i wouldn't have tried again so quickly and sorry for the noise.
