### ISSUE TITLE
Implement Tox Client Standard concerning the avatars

### ISSUE THREAD

**Issue by ovalseven8** [GrayHatter/uTox#45]
Hello,

because it has been merged now, here the issue.

>2.3.5 Clients must display avatars at a 1:1 aspect ratio.

Done by uTox. :white_check_mark: 

>2.3.6 A client may only transmit avatars with an aspect ratio of 1:1. If the user has chosen a non-square avatar, the client must transmit the square portion of the avatar displayed to the user.

**Not done yet. :x:**

Further explanation -> https://github.com/Tox/Tox-Client-Standard/pull/13#issuecomment-149243360

**Comment by GrayHatter** [comment]
no... Someone else can feel free to implement this, and I'll likely merge that PR. But that would require image editing software to be built into uTox.

**Comment by ovalseven8** [comment]
But why closing the issue?

**Comment by GrayHatter** [comment]
Sorry, recurring issue for me. My brain likes the silver button better.

**Comment by tsudoko** [comment]
I think this should be optional, I for one don't want uTox to modify the image I've specified in any way.

**Comment by GrayHatter** [comment]
I don't agree with this tacos standard. Closing, you can try to convince me I'm wrong, but you'll need a strong argument.
