### ISSUE TITLE
Keyboard shortcuts to switch between friends

### ISSUE THREAD

**Issue by Tamriel** [GrayHatter/uTox#51]
Slack uses
Switch to next friend: alt + arrow up/down
Switch to next unread friend: alt + shift + arrow up/down

**Comment by GrayHatter** [comment]
I think @Doom032 is working on a PR for that. IIRC he's using the standard Ctrl + PgUp/PgDn

**Comment by GrayHatter** [comment]
#47

**Comment by GrayHatter** [comment]
@Doom032 I'd say add everything, then we can // out anything that doesn't work. I don't know if I'm going to like ctrl or alt or pg up/dn or arrow left/right, so start with everything then pull out what doesn't work.

Keep in mind, as soon as we add this, someone's going to want to reorder the list with hotkeys, and delete friends, and x and y and z.... 

also it would be nice to be able to hotkey jump to the last activity, eg incoming calls etc how hard would that be?

**Comment by Doom032** [comment]
I do believe every program should have all its functions exposed with both the mouse and the keyboard, so I don't think it's bad that we'd have hotkeys for everything.

What would you mean by "hotkey jump to the last activity"? Like pressing alt+a(or whatever) to get to the newest message or incoming call? You'd need some definition of last activity. Maybe a global that points to an item that's set when you get a new message or incoming call.

**Comment by GrayHatter** [comment]
@Doom032 yeah, that's what I was thinking.

**Comment by GrayHatter** [comment]
in develop
