### ISSUE TITLE
µTox crashes when trying to use proxy with bad proxy settings

### ISSUE THREAD

**Issue by Doom032** [GrayHatter/uTox#54]
If you set proxy to either "Always use" or "Fallback", while the proxy IP and port don't point to a correct proxy, µTox crashes. Of course, that's not nice.

Bad fix, don't do: Making µTox retry without proxy(This would leak information. People are using the proxy because they don't want it to be known what they're connecting to!)

Suggested fix: Add a message in red saying your proxy doesn't work, and don't reconnect to Tox until a different one is entered or proxy is set to "disable"

Look into: What's the "Fallback" option of the proxy setting really doing? Why does it crash if I set it to a bad fallback proxy? Maybe it's not implemented fully.

**Comment by cebe** [comment]
reproduced, code ends up here and uTox will exit:

https://github.com/GrayHatter/uTox/blob/be3f52281ab25fdab61bc7699bd453eca2c34887/tox.c#L517

**Comment by cebe** [comment]
@GrayHatter 

```
new tox object ipv6: 1 udp: 1 proxy: 2  0
trying without proxy, err 6
trying without ipv6, err 6
tox_new() failed 6
```

when I select Proxy: "Fallback" or "Always use"

**Comment by cebe** [comment]
![bildschirmfoto von 2015-12-20 04 37 59](https://cloud.githubusercontent.com/assets/189796/11916352/7ddc0c7e-a6d3-11e5-869b-4d81f999bf2f.png)

selecting proxy here without entering IP or Port.

**Comment by GrayHatter** [comment]
fixed in encrypt_save

**Comment by linux0ne** [comment]
utox 0.5.0   ---------------   crashes when trying to use set proxy with bad proxy settings

**Comment by cebe** [comment]
@linux0ne this particular issue has been fixed, please open a new one and provide steps to reproduce it.
