### ISSUE TITLE
preview window does not close if opening video device failed

### ISSUE THREAD

**Issue by cebe** [GrayHatter/uTox#56]
steps to reproduce:

- go to settings "Audio/Video"
- select desktop input
- start preview
- ensure camera is locked by another program (e.g. view it in Cheese when on debian or ubuntu)
- change video input to the locked camera

utox will fail to open the video input but does neither report it nor close the preview window.

**Comment by cebe** [comment]
related:

> uToxVID:	End of video record... (65535)
> uToxVID:	Exceeded max calls, abort abort!!

we should ensure the `video_count` does not become negative.

**Comment by GrayHatter** [comment]
@cebe that's what that last warning is doing. But as you can see there's no checks before incrementing/decrementing `video_count`
