### ISSUE TITLE
File transfer layout glitch

### ISSUE THREAD

**Issue by cebe** [GrayHatter/uTox#57]
buttons are missing the left padding:
![bildschirmfoto von 2015-11-19 13 35 11](https://cloud.githubusercontent.com/assets/189796/11270866/aa3b4a1a-8ec2-11e5-9b4e-dd4c127e6ec7.png)

**Comment by cebe** [comment]
here are three proposals on how this could be fixed:

Make the buttons with rounded corners and center the icon:
![bildschirmfoto](https://cloud.githubusercontent.com/assets/189796/11273206/3ea2999c-8ed2-11e5-959b-4a55a20207a7.png)

I also think the text and progress bar should be aligned with chat message text.
Also buttons should have some margin around them.

![bildschirmfoto2](https://cloud.githubusercontent.com/assets/189796/11273207/3ea737ea-8ed2-11e5-9349-a54cff24c9c0.png)

This is the same as before but buttons are inside the chat message space, not in the time column:
![bildschirmfoto3](https://cloud.githubusercontent.com/assets/189796/11273208/3ea9e0f8-8ed2-11e5-9012-01603476f1a1.png)

what do you think?

**Comment by mannol** [comment]
3rd

**Comment by GrayHatter** [comment]
@cebe take a look at https://github.com/GrayHatter/uTox/tree/ui-rev3 I'm inprogress of pulling the edges back inside the text area (i.e. not over the name or the time). Other than that, mannol's right 3rd.

**Comment by nurupo** [comment]
When you send a file, does it show in the message view who is the sender?

From these screenshots, I see that this information if not part of the file transfer widget. Am I right to assume that a new line with sender's name and the time is added before the widget?

**Comment by nurupo** [comment]
Oh, nevermind, I see in https://github.com/GrayHatter/uTox/issues/57#issue-117805383

**Comment by cebe** [comment]
no, there is no name of the sender, "Test" was a message sent before the file transfer.

**Comment by nurupo** [comment]
Oh, I got confused. Thought "Test" was actually a name of the user.

Imagine you have a situation where Alice sends text messages and Bob decides to send a file, without writing any messages. If it's not said that the file is being sent by Bob, Alice might thing that it's something she did. It also won't be very obvious that it was bob who sent the file when reading the chat log, where the file transfer is complete.

**Comment by cebe** [comment]
okay, the name is displayed but only if this is the first message:

![bildschirmfoto von 2015-11-19 17 39 01](https://cloud.githubusercontent.com/assets/189796/11276956/871c70f0-8ee4-11e5-8a12-812336ad65c9.png)

imo the name should always be added, same as for /me messages.

Also I think it looks better when the color of the file transfer background covers the whole row as in my screenshots above (screen in this comment is on the ui-rev3 branch).

**Comment by nurupo** [comment]
>okay, the name is displayed but only if this is the first message:

Oh, it's fine then.

**Comment by cebe** [comment]
maybe this looks even better:
![filetransfer_v2](https://cloud.githubusercontent.com/assets/189796/11277368/8bce8640-8ee6-11e5-8abd-b1a2493f2615.png)

**Comment by nurupo** [comment]
The second time seems to be misaligned with the first one by a few pixels.

**Comment by cebe** [comment]
yeah, this is just a quick draft, drawn in gimp ;)

**Comment by GrayHatter** [comment]
@cebe somewhere in ui.h or svg.h there's a bitmap "cap" for that left rounded corner.

I might have deleted it, I don't remember. Either way, I'd like to use an end cap, instead of drawing that whole bar in svg.c

if you can shrink the bar, and align the text in messages.c, I'll add and draw the end cap if you can't find it/don't have 2 weeks to learn svg.c

**Comment by GrayHatter** [comment]
@cebe make sure any PR you make goes to the ui-rev3 branch

**Comment by cebe** [comment]
sure, so the last image I made is how it should look like?

**Comment by GrayHatter** [comment]
I think it looks good, go for it!

**Comment by GrayHatter** [comment]
thanks for fixing this stal
