### ISSUE TITLE
Feature: Showing full date in message log when it's a different day

### ISSUE THREAD

**Issue by Doom032** [GrayHatter/uTox#65]
As it is now, it can be confusing when stuff like this happens:

```
[Bob] How are you? - 13:30
[Alice] Fine - 13:39
[Bob] ... I sent that message a week ago. - 13:40
```

I'd like a date header for the first message in the log, and after each that is of a different date, like this:
```
   *Thursday, 17 November 2015*
[Bob] How are you? - 13:30
   *Saturday, 22 November 2015*
[Alice] Sorry, I didn't see your message! - 13:39
[Bob] You just wanted to ignore me ;_; - 13:40
```

The date header should have its own colour(probably grey in default theme, but should be editable per theme).

**Comment by GrayHatter** [comment]
done
