### ISSUE TITLE
bug combining greentext and redtext

### ISSUE THREAD

**Issue by Doom032** [GrayHatter/uTox#72]
Write this message in µTox:
```
> red text<
This shouldn't be green, but it is.
```

For some reason the lines after a red text starting with a > are turned to green text. Maybe erroneously setting the colour back to whatever its previous value was?

**Comment by GrayHatter** [comment]
@Doom032 should be fixed in d37192ed11e0082e84e21444fed9245f0ccd9fa5

**Comment by Doom032** [comment]
@GrayHatter that fixes it for me.
