### ISSUE TITLE
guide fo utox compilation on Tails

### ISSUE THREAD

**Issue by naviduett** [GrayHatter/uTox#80]
Hi every one.

I have written an article on utox compilation on Tails distribution. I could not find email if of maintainer however i am sharing here link for uTox compilation.

http://linoxide.com/security/install-utox-client-tails/

Please include it in uTox ReadMe/Install file.

**Comment by danielisaksen** [comment]
@naviduett I would suggest fixing up the grammar and whitespace before making a pull request on it. Also, I would suggest running `make -j $(nproc)` as that would run make with one thread per CPU, making compilation noticeably faster.

**Comment by naviduett** [comment]
@danielisaksen okay sir. i will fix in version 2
