### ISSUE TITLE
OS X: uTox crashes when typing

### ISSUE THREAD

**Issue by giggle-engineer** [GrayHatter/uTox#86]
Very often uTox will crash when typing into the chat box. I've attached a crash log. 
[utox_2015-12-09-171206_book.crash.txt](https://github.com/GrayHatter/uTox/files/57532/utox_2015-12-09-171206_book.crash.txt)

**Comment by stal888** [comment]
try latest please

**Comment by giggle-engineer** [comment]
That is with the latest.

**Comment by giggle-engineer** [comment]
My mistake, trying now.

**Comment by stal888** [comment]
no worries, i committed it after reading this anyway

**Comment by giggle-engineer** [comment]
So far so good. If it doesn't crash within the next 24 hours then I'll close it.
