### ISSUE TITLE
OS X: Typing notification too low

### ISSUE THREAD

**Issue by giggle-engineer** [GrayHatter/uTox#87]
The typing notification label is too low. The g overlaps and goes into the chat box. My guess on the possible cause would be that it's because I'm using a retina display.

<img width="139" alt="typing notification" src="https://cloud.githubusercontent.com/assets/7425159/11704100/8e72f698-9e99-11e5-8978-1ccd52734b61.png">

**Comment by GrayHatter** [comment]
no, I fixed this, now it's unfixed... I don't even remember changing anything...
