### ISSUE TITLE
GTK file chooser doesn't preview images

### ISSUE THREAD

**Issue by tsudoko** [GrayHatter/uTox#93]
It can be done since Firefox and GIMP use the GTK file chooser and it does preview images.
![](https://a.pomf.cat/uexffb.png)

**Comment by benwaffle** [comment]
I think i can do it
https://bug396876.bmoattachments.org/attachment.cgi?id=293732

**Comment by cebe** [comment]
here is the documentation about this feature: https://developer.gnome.org/gtk3/stable/GtkFileChooser.html#id-1.3.14.6.11.6 seems they do not provide a default implementation for file preview so we have to add one ourselfs.

**Comment by benwaffle** [comment]
see PR #108

**Comment by tsudoko** [comment]
Closed in #120
