### ISSUE TITLE
[Feature request] Meta-contacts (unite/group several contacs in one)

### ISSUE THREAD

**Issue by redmanmale** [GrayHatter/uTox#97]
As I said before (here https://github.com/notsecure/uTox/issues/1131), this will be very useful feature.

For example, some people in my contact list have already two or three different accounts for home/work/laptop/PC and it started to be a problem to find in which chat we discuss what I am searching for.

And I think I'm not the only one with that problem.

**Comment by cebe** [comment]
As far as I see there are two solutions to this problem:

1. The one you suggest for being able to group contacts in the client. This solution can be implementent in clients such as uTox.
2. Being able to use the same account from different devices (and being online at the same time).
  This would have to be implemented at toxcore.

**Comment by ProMcTagonist** [comment]
Isotoxin has implemented this. https://wiki.tox.chat/clients/isotoxin

**Comment by GrayHatter** [comment]
I'm going to close this because I'm never going to implament this in uTox. I may consider Pull Requests on this.

The reason I'm never going to implement this, is I'm currently writing Multi Device support into toxcore. So instead of having grouped contacts, uTox will have REAL multidevice support.
